### ISSUE TITLE
Allow Adapter to specify Default Schema

### ISSUE THREAD

**Issue by ThatRendle** [ThatRendle/Simple.Data#105]
Currently, default schema is specified in config. Should allow Adapter to provide a value, and AdoAdapter should defer this to the Provider.

**Comment by ThatRendle** [comment]
Question: what is the ANSI standard terminology for schema / owner?

**Comment by richardhopton** [comment]
Not sure about ANSI but... (in abbreviated form)

SQL Server Books Online = CREATE TABLE schema_name.table_name 
Sybase Manual = CREATE TABLE owner.table-name
Oracle Manual = CREATE TABLE schema.table

Based on that the concensus is Schema, and in SQL Server (at least) Schema & Owner are not interchangable.

**Comment by ThatRendle** [comment]
Yep, the "schema" has it. That's the term in PostgreSQL too.

**Comment by ThatRendle** [comment]
Oh, yeah. Done.
