### ISSUE TITLE
Homogenization

### ISSUE THREAD

**Issue by craiggwilson** [ThatRendle/Simple.Data#11]
One more place it looks like I forgot to kill.  ConcreteTypeCreator line 41 needs to have the homogenization removed.  This means that whatever dictionary the adapter passes in is how keys will get compared.  Ado uses a HomogenizedKeyComparer, while Mongo will use a CaseSensitive one.

**Comment by ThatRendle** [comment]
Fixed. Went through and found other superfluous calls to Homogenize() and killed them while I was at it.

**Comment by craiggwilson** [comment]
Awesome, I saw that.  Once you push .5 to nuget, I'll have the mongodb one reference your nuspec and push the adapter up as well.

BTW: I noticed that the Core nuspec file includes the Ado stuff.  Any reason for that?

**Comment by ThatRendle** [comment]
Mainly that I wasn't expecting a NoSQL adapter so soon!

**Comment by ThatRendle** [comment]
BTW, do you have a Twitter handle? I want to make a contributors list.

**Comment by craiggwilson** [comment]
My twitter handle is craiggwilson, but I don't really follow much on twitter.  You can just include my github account (craiggwilson) or my email (craiggwilson@gmail.com).

Thanks.
