### ISSUE TITLE
Simple.Data.Pad 0.7.2

### ISSUE THREAD

**Issue by zhanghuansss** [ThatRendle/Simple.Data#110]
dbo.Users.Find(dbo.Users.ID % 2 == 0  || (dbo.Users.Name == '2' && dbo.Users.ID == 1))

Simple.Data.Ado: 
Text
select [dbo].[Users].\* from [dbo].[Users]  where ([dbo].[Users].[ID] \* 20 = @p1 OR ([dbo].[Users].[Name] = @p2 AND [dbo].[Users].[ID] = @p3))
@p1 (AnsiString) = 0
@p2 (String) = 2
@p3 (Int32) = 1

**Comment by richardhopton** [comment]
Is it safe to say that this issue (@p1 being an AnsiString) is covered by issue 106?

**Comment by ThatRendle** [comment]
Yup.
