### ISSUE TITLE
Incorrect max length reported by Sql Server for certain columns

### ISSUE THREAD

**Issue by richardhopton** [ThatRendle/Simple.Data#114]
The fix for 113 involved using the size of the column along with the data type etc.  Unfortunalety this highlighted the following:-
IMAGE, TEXT & NTEXT are reported as having a max length of 16, when in fact they can support 2GB of data.
NVARCHAR & NCHAR are reported as having a max length of twice their actual length.

**Comment by Mpdreamz** [comment]
Pinpointed this one down as well was going to fix it but just in time noticed your branch has this one fixed already, sweet!

**Comment by richardhopton** [comment]
There's an outstanding pull request for this issue so it should be resolved in the standard build as soon as Mark merges it.

**Comment by Mpdreamz** [comment]
Works like a charm, this should be pulled and pushed to nuget asap.
