### ISSUE TITLE
Add possibility to disable trace output

### ISSUE THREAD

**Issue by mariusin79** [ThatRendle/Simple.Data#115]
I think it should be able to disable the trace output from an app.config file. We are using Simple.Data and the tracing output is obfuscating the output from our integration tests.

**Comment by ThatRendle** [comment]
Done in 0.11. See http://blog.markrendle.net/2011/11/24/simple-data-0-11/ for details.

**Comment by ploeh** [comment]
The above blog post describes a configuration approach which has subsequently been deprecated. For reference, this seems to work:

``` XML
  <system.diagnostics>
    <switches>
      <add name="Simple.Data" value="Error" />
    </switches>
  </system.diagnostics>
```

I'm just posting it here for the benefit of any other person who may come by this page, as this was basically the only hit I could get out of Google.
