### ISSUE TITLE
Suggestion: Sql TOP

### ISSUE THREAD

**Issue by thinkdevcode** [ThatRendle/Simple.Data#117]
Would it be possible to support the TOP sql command?

Edit: Or even better, have a system for paging results.

**Comment by richardhopton** [comment]
The system supports paging on queries using the Skip and Take keywords. eg:- 
db.MyTable.Query().OrderByMyField().Skip(10).Take(10)

Take a look at QueryTest.cs to see it being used.

**Comment by ThatRendle** [comment]
Since 0.11, SQL Server will use TOP 1 as an optimisation for all single-record queries. As Richard has said, paging is already fully supported using different implementations per provider.
