### ISSUE TITLE
Catching DBnull values during implicit casting

### ISSUE THREAD

**Issue by Vidarls** [ThatRendle/Simple.Data#12]
I somehow ended up with a bunch of Null values in my test db, and this caused argument exceptions when I ran my find tests.
The exceptions originated in the ConcreteTypeCreator class TryCreate method.
I found that adding two lines of code fixed this:
(Added :
if (value == dbnull.value)
value = null;

My git foo is a bit rusty, and for some reason when I change anything, Git insists on producing a diff that removes all lines, and then re adds them, so a git commit + pull req would be useless until I figure this out, so pasted code is all I can bring now..

public bool TryCreate(IDictionary<string, object> data, out object result)
        {
            bool anyPropertiesSet = false;
            object obj = Activator.CreateInstance(_concreteType);
            object value;
            foreach (var propertyInfo in _concreteType.GetProperties().Where(pi => CanSetProperty(pi, data)))
            {
                value = data[propertyInfo.Name.Homogenize()];

```
            if (ConcreteCollectionTypeCreator.IsCollectionType(propertyInfo.PropertyType))
            {
                if (!ConcreteCollectionTypeCreator.TryCreate(propertyInfo.PropertyType, (IEnumerable)value, out value))
                    continue;
            }
            else
            {
                var subData = value as IDictionary<string, object>;
                if (subData != null && !ConcreteTypeCreator.Get(propertyInfo.PropertyType).TryCreate(subData, out value))
                    continue;
            }

            if (value == DBNull.Value)
                value = null;

            propertyInfo.SetValue(obj, value, null);
            anyPropertiesSet = true;
        }

        result = anyPropertiesSet ? obj : null;

        return anyPropertiesSet;
```

**Comment by craiggwilson** [comment]
I don't think this belongs in the ConcreteTypeCreator.  Rather, it should exist in the Ado Adapter somewhere because it does not pertain to all data sources, but rather specifically towards sql oriented ones.

**Comment by ThatRendle** [comment]
I've added code to the AdoAdapter to map DBNull values to CLR nulls. Code is in latest master branch.

**Comment by Vidarls** [comment]
Great! Agree that this belongs in AdoAdapter.
