### ISSUE TITLE
UseSharedConnection is completely wrong

### ISSUE THREAD

**Issue by ThatRendle** [ThatRendle/Simple.Data#126]
The UseSharedConnection method sets the connection at the adapter level, and the adapter is shared by all database objects because it's cached. This is because you are an idiot.

Since you already released this API, the best solution would be to have an adapter per database instance. I suspect there are other good reasons for this approach to. So optimise the AdoAdapter creation code to create new adapters but with shared stuff like schema info.

Seriously, I despair of you sometimes.

**Comment by craiggwilson** [comment]
Wow Mark.  No need for such disparaging comments about yourself.  You should let someone else do that for you.  :)

**Comment by ThatRendle** [comment]
Fixed in 0.11.3.2.
