### ISSUE TITLE
InvalidOperationException when running LIKE query after another

### ISSUE THREAD

**Issue by mikebrind** [ThatRendle/Simple.Data#13]
This works:
    var db = SD.Database.OpenFile(Server.MapPath("~/App_Data/Northwind.sdf"));
    var data = db.Products.FindAll(db.Products.ProductName.Like("C%"));
    var products = db.Products.FindAll(db.Products.CategoryId == 4);

Whereas this throws an InvalidOperationException (Operation is not valid due to the current state of the object):
    var db = SD.Database.OpenFile(Server.MapPath("~/App_Data/Northwind.sdf"));
    var products = db.Products.FindAll(db.Products.CategoryId == 4);
    var data = db.Products.FindAll(db.Products.ProductName.Like("C%"));

**Comment by ThatRendle** [comment]
Good catch, thanks! Fixed in latest commit, will push to Nuget soon.
