### ISSUE TITLE
SQL NOT LIKE

### ISSUE THREAD

**Issue by nkaiseng** [ThatRendle/Simple.Data#131]
Hi All,

Can you help me with this one! 
I know you can do something like, //LIKE 
{ 
  var results = 
db.priorityTypes.FindAll(db.priorityTypes.PriorityType.Like("monitoring")); // 
From priorityTypes 
} 
BUT how about NOT LIKE 
select \* from prioritytypes where PriorityType not like "monitoring"

**Comment by t3hc13h** [comment]
It looks like all you'd need to do is add "notlike" to AdoAdapter.IsExpressionFunction as it's already been provided for it in ExpressionFormatterBase.FunctionExpressionToWhereClause. It seems to work in my ad-hoc tests.

**Comment by richardhopton** [comment]
@t3hc13h - We accept pull requests you know! :-)

**Comment by t3hc13h** [comment]
I'd be more than happy to submit a pull request but this is the best I could do for the time being. I'll be sure to submit one when I get the chance.

**Comment by richardhopton** [comment]
Ok - thanks for the heads up; I'll fix this tonight

**Comment by richardhopton** [comment]
Code and tests are available for this now.

**Comment by nkaiseng** [comment]
It looks like all you'd need to do is add "notlike" to AdoAdapter.IsExpressionFunction as it's already been provided for it in ExpressionFormatterBase.FunctionExpressionToWhereClause. It seems to work in my ad-hoc tests.

HOW DO I DO THAT?

**Comment by richardhopton** [comment]
Hi @nkaiseng 

This change has been made and will form part of the next update to Simple.Data.  If you fancy you can fork or just grab the code and build the updated Simple.Data yourself.

Thanks

Richard
