### ISSUE TITLE
Execute a stored procedure from a string name

### ISSUE THREAD

**Issue by achvaicer** [ThatRendle/Simple.Data#132]
There is a way to execute a stored procedure knowing the name dynamically?
Something like
db.ExecuteStoreProcedure("store_procedure_name", params);

**Comment by richardhopton** [comment]
This could be a nice pattern such as...

var someProc = db["stored_procedure_name"];
var result = someProc(params);

It would allow you to store and reuse a procedure ref in much the same way as you would with a delegate or method group

I'll take a look at what's involved with implementing this and get back to you.

**Comment by achvaicer** [comment]
Thanks, man!

**Comment by ThatRendle** [comment]
Not at present. I will add this to the roadmap.
