### ISSUE TITLE
Decimal SQL type

### ISSUE THREAD

**Issue by cairey** [ThatRendle/Simple.Data#139]
Doesn't seem to be supported? It's rounding to the nearest whole number.

**Comment by ThatRendle** [comment]
In what context? Reading or writing? It is supported, so if you're not getting it that's a bug somewhere. Could you post some code to reproduce the problem?

Thanks,
Mark

**Comment by cairey** [comment]
I didn't test reading but there is an issue with writing. PriceExcVat in this example is a decimal. It will save to the DB but only as a whole number. For now I'm using a float DB type, which works.

```
        var database = Database.OpenConnection(_configuration.ConnectionString);
        var item = new Item()
        {
            Id = Guid.NewGuid(),
            Title = package.Title,
            UserId = package.UserId,
            PriceExcVat = package.PriceExcVat,
            CategoryId = package.CategoryId
        };

        database.Items.Insert(item);
```

Thanks
Chris

**Comment by richardhopton** [comment]
Hi Chris,

Can you confirm the schema for the table?

I've added a bunch of tests for Decimal data types and it inserts and retrieves correctly. I'll commit them later.

Thanks,

Richard

**Comment by cairey** [comment]
Hi,

Thanks for looking into this, however I can confirm that it is our error. Someone has set up the decimal type to have 0 right hand digits, I have set this accordingly and it it works as expected.

Thanks
Chris
