### ISSUE TITLE
Transaction Support with InMemoryAdapter

### ISSUE THREAD

**Issue by Molokai** [ThatRendle/Simple.Data#140]
Given:

`var db = Database.UseMockAdapter(new InMemoryAdapter());`
`db.BeginTransaction()` 

throws NotSupportedException - "Specified method is not supported"

Is there any recommended way to use both transactions AND unit tests with the InMemoryAdapter?

I guess I could just subclass the InMemoryAdapter and implement a dummy IAdapterWithTransactions which just calls the non-transactional methods and implements empty commit/rollback methods.

Or are there better approaches?

<b>Update:</b>
I just did a quick and dirty subclassing as per my previous comment. Tests come out in green, so that solves the issue for me.

https://gist.github.com/1665747#file_in_memory_adapter_with_shim_transactions.cs

**Comment by ThatRendle** [comment]
That's an oversight. I'll fix and release in 0.14, which will be out by end of the week.

Mark

**Comment by Molokai** [comment]
Sounds great!

When doing that - also consider that people will want to write natural joins while unit testing with the InMemoryAdapter. I presume this might/could be possible by providing a mock schema?

**Comment by ThatRendle** [comment]
There is facility for setting up relationships in the InMemoryAdapter, although the syntax is awful and I'm going to improve it.

**Comment by ThatRendle** [comment]
InMemoryAdapter will now not throw an exception when a Transaction is used, although CRUD operations are not actually transactional yet.

**Comment by Molokai** [comment]
Works for me.
