### ISSUE TITLE
status on upserts?

### ISSUE THREAD

**Issue by Molokai** [ThatRendle/Simple.Data#141]
Upserts are mentioned in this blog post:

http://blog.markrendle.net/2011/12/01/eager-loading-rfc/

But searching the source code, there are no references to "upsert". Is this feature implemented? If so, how is it used?

**Comment by okify** [comment]
I'm going to be releasing the With feature mentioned in that post in the
next day or two, then moving on to Upsert.

Cheers,
Mark

On 24 January 2012 18:03, Molokai <
reply@reply.github.com
