### ISSUE TITLE
Composite keys

### ISSUE THREAD

**Issue by Molokai** [ThatRendle/Simple.Data#145]
I have not managed to find anything about composite keys - What is the simple.data story regarding composite keys?

**Comment by ThatRendle** [comment]
I'm not sure what you're asking about, but the AdoAdapter fully supports composite keys for Get, natural joins and key-based updates and deletes.

For example, an Order table with a composite key of CustomerId and OrderId:

var order = db.Orders.Get(cid,oid);
order.Shipped = true;
db.Orders.Update(order);
