### ISSUE TITLE
OderBy Asc

### ISSUE THREAD

**Issue by nkaiseng** [ThatRendle/Simple.Data#152]
This what I've done so far!

How do I sort by "ascending" 

 var var_Jobs = db.jobs.FindAllByloggedbyAndjobstatus(loggedby: lngLoggedByID, jobstatus: "o").OrderByLogged_at();

**Comment by ThatRendle** [comment]
That does order by ascending.

If you want to do descending, use OrderByLoggedAtDescending.

A couple of notes: where you're using a FindByXAndY method, you don't need
to name the parameters, the column names are extracted from the method name.
Also, the AdoAdapter is not case and underscore sensitive, so feel free to
PascalCase all your object names:

var jobs = db.Jobs.FindAllByLoggedByAndJobStatus(lngLoggedByID,
"o").OrderByLoggedAtDescending();

M

On Wed, Feb 15, 2012 at 9:39 AM, nkaiseng <
reply@reply.github.com

**Comment by nkaiseng** [comment]
Thank You :-) :-)
