### ISSUE TITLE
LIMIT

### ISSUE THREAD

**Issue by nkaiseng** [ThatRendle/Simple.Data#153]
How do we perform limit:

{select \* from schdowntime limit 5}

**Comment by ThatRendle** [comment]
db.SchDownTime.All().Take(5)

**Comment by findel** [comment]
Should that be FindAll()?

**Comment by ThatRendle** [comment]
No, .All() works.

**Comment by findel** [comment]
Ok, thanks. 

I seem to get an error if I use `.All()`, but no error if I use `.FindAll()`

```
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot convert type 'Simple.Data.SimpleQuery' to 'System.Collections.Generic.List'
```

Probably something I'm doing wrong, right?

**Comment by findel** [comment]
Ignore me. I needed to `.All().ToList<MyModel>()`. Stupid me.
