### ISSUE TITLE
Eager fetching with child item in query requires correlation

### ISSUE THREAD

**Issue by morganjohnston** [ThatRendle/Simple.Data#157]
A query with eager fetching such as: db.Customer.FindAll(db.Customer.Order.Id == orderId).WithOrders().ToList<Customer>();
causes the following error: "Simple.Data.Ado.AdoAdapterException : The objects "dbo.Order" and "dbo.Order" in the FROM clause have the same exposed names. Use correlation names to distinguish them."

**Comment by ThatRendle** [comment]
That was an interesting one. Seemed to be because the object name in the criteria (Order) was not exactly the same as on the With (Orders), threw off the joining code.

Fixed.
