### ISSUE TITLE
TraceInformation is called by Ado.ProcedureExecutor regardless of Database.TraceLevel

### ISSUE THREAD

**Issue by saggett** [ThatRendle/Simple.Data#159]
Method ExecuteNonQuery(IDbCommand command) on Simple.Data.Ado.ProcedureExecutor executes Trace.TraceInformation("ExecuteNonQuery", "Simple.Data.SqlTest") without checking Database.TraceLevel.

**Comment by ThatRendle** [comment]
Fixed, thanks for reporting.
