### ISSUE TITLE
Ability to insert child entity items?

### ISSUE THREAD

**Issue by morganjohnston** [ThatRendle/Simple.Data#160]
If I have a class, Customer which contains a List<Order> Orders. It seems that there is no way of specifying that I would like this also saved and instead I need to write a separate Insert statement for Orders.  Not terrible, and this might be by design? but would be neat for Simple.Data to handle that too :)

**Comment by ThatRendle** [comment]
Doing that kind of thing becomes enormously complicated, having to watch out for circular references and such-like. Also you would expect Orders that had been removed from the List to be deleted from the database, which requires tracking of List deletions, and it's all just too much. So I'm afraid you'll just have to be explicit, although remembed that you can just call db.Orders.Upsert(customer.Orders) (making sure you've set the CustomerId value first, of course!).

**Comment by morganjohnston** [comment]
Ok, fair enough :)
