### ISSUE TITLE
Eager fetching query issues returning multiple parent items

### ISSUE THREAD

**Issue by morganjohnston** [ThatRendle/Simple.Data#161]
It seems the eager fetching can't handle returning multiple parent items. For example:

For All()
db.Customer.All().ToList<Customer>(); // Works
db.Customer.All().WithOrders().ToList<Customer>(); // Throws ArgumentOutOfRangeException "Index was out of range. Must be non-negative and less than the size of the collection".

For FindAll()
db.Customer.FindAll(db.Customer.Name == "Rambo").WithOrders().FirstOrDefault(); // This works because the query only returns a single row

db.Customer.FindAll(db.Customer.Name == "Generic Name").WithOrders().FirstOrDefault(); // Returns multiple rows so also throws ArgumentOutOfRangeException "Index was out of range. Must be non-negative and less than the size of the collection."

**Comment by ThatRendle** [comment]
Are you still seeing this behaviour with 1.0.0-beta2? I think I fixed it in that release, but if you can confirm that I can close this issue.

**Comment by maniserowicz** [comment]
hi, i can only confirm that i also experienced this behaviour in beta1, but works just fine in beta2

**Comment by ThatRendle** [comment]
Excellent.
