### ISSUE TITLE
Need method to reset InMemory database (for example between tests and fixtures)

### ISSUE THREAD

**Issue by saggett** [ThatRendle/Simple.Data#162]
Between unit tests I would like a way to entirely empty the in memory database of schema and data.

Also a means to stop using a mock adapter (reverting the effect of calling Database.UseMockAdapter(...)) would be nice.

**Comment by ThatRendle** [comment]
The way to empty it is to create a new InMemoryAdapter and call UseMockAdapter again. I will add a method to stop using it.
