### ISSUE TITLE
User-defined types in SQL Server causing crash

### ISSUE THREAD

**Issue by ThatRendle** [ThatRendle/Simple.Data#163]
When a table contains a User-Defined type (including Geography or Geometry) column, the SqlSchemaProvider crashes.

**Comment by ThatRendle** [comment]
Fixed, although still no actual handling for user-defined types.

**Comment by hmobius** [comment]
Is there any further progress on actual handling for user-defined types yet?

**Comment by BoasE** [comment]
Any news on this ?
