### ISSUE TITLE
Method Documentation

### ISSUE THREAD

**Issue by madness2222** [ThatRendle/Simple.Data#166]
Hi,

I've been using Simple.Data for the last few days and I've find it very very useful. As I am aware the library itself utilises dynamic variables as a result there are no intellisense.

I've googled and looked at sample app for a more complete list of methods it is available and sample on how to use it. But, the information on that it is very scarce.

Is there a reference list floating around the internet somewhere, if there is can you point me to the direction where I can find them?

Many Thanks

**Comment by ThatRendle** [comment]
I'm working on fuller documentation at the moment. In the meantime, the best place to look is in the test projects in the solution; that's where I'm pulling the docs from.
