### ISSUE TITLE
Issue with nested FindAlls and SqlCompact40

### ISSUE THREAD

**Issue by timhall** [ThatRendle/Simple.Data#167]
As originally described in http://stackoverflow.com/questions/9503809/simple-data-many-to-many-issues, the following code works well when there is only one record in the first FindAll, but fails with the following exception when there is more than one record:

Index was out of range. Must be non-negative and less than the size of the collection.

I'm using Simple.Data.Core, .Ado, and .SqlCompact40 1.0.0beta3

Here is all of the code for the class:

``` cs
public class ContractorRepository : IContractorRepository {
    dynamic _db;
    public TradeAllyRepository() {
        string dbPath = AppDomain.CurrentDomain.GetData("DataDirectory").ToString() + "\\Contractors.sdf";
        _db = Simple.Data.Database.Opener.OpenFile(dbPath);
    }

    public dynamic GetAllForZip(int zip) {
        var contractors = _db.Contractors
            .FindAll(_db.Contractors.CoverageZips.Zip == zip)
            .ToList();

        foreach (var contractor in contractors) {
            // Exception occurs here after working successfully for first iteration
            contractor.Types = GetTypesForContractor((int)contractor.Id);
        }

        return contractors;
    }

    public dynamic GetTypesForContractor(int id) {
        return _db.ContractorTypes
            .FindAll(_db.ContractorTypes.TypesForContractor.ContractorId == id)
            .ToList();
    }
}
```

I watched it with the debugger and looking at Dynamic view for `contractor` in the `foreach` it displays fine the first time and on the second time it displays: 

```
base {System.ArgumentException} = {"Index was out of range. Must be non-negative and less than the size of the collection.\r\nParameter name: index"}
```

If I had to guess (and this is based on a pretty basic understanding of this excellent library), the query isn't being executed until it is needed (which is good), but the second `FindAll` (in `GetTypesForContractor`) is crossing paths with the first and on the second iteration of the `foreach` the query has been lost. Is there a way for me to tell it to actually execute the query when it first loads `contractors` so that it has the actual values rather than the "deferred" values (I'm not sure if that is the right word)?

Thanks for the awesome library!

**Comment by ThatRendle** [comment]
Hi, thanks for opening the issue. I'll get some time to look into it on Friday.
