### ISSUE TITLE
Can't Trace SQL :(

### ISSUE THREAD

**Issue by ronnieoverby** [ThatRendle/Simple.Data#170]
I'm using Simple.Data.SqlServer from Nuget (0.14.0.3)

I add a trace Listener and set Database.TraceLevel: 

```
        Trace.Listeners.Add(new HappyTraceListener());
        Database.TraceLevel = TraceLevel.Info;
```

Never see any generated SQL.

What am I doing wrong?

**Comment by ronnieoverby** [comment]
I have found that when doing ADO queries that have .WithTotalCount(out count) in them, the SQL isn't written by Trace.

**Comment by ThatRendle** [comment]
Yeah, there are still a few places where the SQL trace doesn't happen, I'm tracking them all down for the next release.

**Comment by ThatRendle** [comment]
OK, I think I've caught all of these now.
