### ISSUE TITLE
Updating Row with timestamp(rowversion) column

### ISSUE THREAD

**Issue by madness2222** [ThatRendle/Simple.Data#175]
HI, 

I've encounter an problem where I'm doing update on a table that has timestamp  column. The error is throwing back Cannot update a timestamp column.|Simple.Data.Ado.AdoAdapterException|AdoAdapterException|Simple.Data.Ado.AdoAdapterException: Cannot update a timestamp column.

From what I understand timestamp is managed by the server, so how do I go about updating the row with timestamp column?

Many Thanks.

**Comment by ThatRendle** [comment]
Fixed. Apologies for the inconvenience.
