### ISSUE TITLE
Do nullable columns become nullable types ?

### ISSUE THREAD

**Issue by kostaswonga** [ThatRendle/Simple.Data#176]
Hi, 
I got a column in mssql which is nullable datetime.

Then i try to access it via..

db.Table.FindById(1).ClosedOn.HasValue 

It seems that the field is not nullable but simply null. Do I miss something ?

Kostas

**Comment by ThatRendle** [comment]
Hi Kostas,

In that example, you're working with the dynamic type returned by Simple.Data, in which NULL values are represented as a `null` object, so you can just say

``` csharp
db.Table.FindById(1).ClosedOn == null
```

If you have a static type for which the ClosedOn property is a Nullable<DateTime> then the auto-casting will handle that and you'll get the HasValue functionality:

``` csharp
class Table
{
    public DateTime? ClosedOn { get; set; }
}

Table t = db.Table.FindById(1);
Assert.True(t.ClosedOn.HasValue);
```

**Comment by kostaswonga** [comment]
Thanks for the swift response Mark!
