### ISSUE TITLE
UpdateAll in 0.16.0.0

### ISSUE THREAD

**Issue by ghost** [ThatRendle/Simple.Data#178]
After upgraging to 0.16.0.0 (from 0.12.x.x), calling UpdateAll when no records match the condition returns an InvalidOperationException: the source contains no datarows. In previous versions, no operation is executed and no error is thrown, which I would think would be the expected behavior. Having to add try/catch everywhere would really be a chore!

Here is the syntax I use:

db.MySchema.MyTable.UpdateAll(
                    db.MySchema.MyTable.Id == id
                    && db.MySchema.MyTable.Status == null,
                    MyColumn1: "value1",
                    MyColumn2: "value2");

Thanks for looking into this.

**Comment by ThatRendle** [comment]
Oops. I'll take a look at that this weekend.
