### ISSUE TITLE
WithOne() doesn't work on FindBy(), only on FindAllBy()

### ISSUE THREAD

**Issue by jhovgaard** [ThatRendle/Simple.Data#185]
Works:

``` C#
public Job GetById(int id) {
    return Table.FindAllById(id)
        .WithOne(Table.Companies.As("Company")).FirstOrDefault();
}
```

Doesn't work:

``` C#
public Job GetById(int id) {
    return Table.FindById(id)
        .WithOne(Table.Companies.As("Company"));
}
```

**Comment by ThatRendle** [comment]
You have to prefix the WithOne call on FindBy:

Table.WithOne(Table.Companies.As("Company").FindById(1);

Reason being that the FindBy methods return the object directly, there's no lazy stuff happening.

**Comment by jhovgaard** [comment]
Ahh makes sense, and yes it is working now :-)

I'm kinda afraid that this kills "The super-duper-happy-path". Is it possible to throw an explaining exception if With() is being called after FindBy()?

**Comment by ThatRendle** [comment]
Explanatory exceptions are always kind of difficult. I'm trying to eliminate all the RuntimeBinderExceptions at the moment and replace them with some more context-aware exceptions with useful messages, but I'm wary of trying to teach by exception.
