### ISSUE TITLE
Get throws exception if row does not exist with given PK value

### ISSUE THREAD

**Issue by hmobius** [ThatRendle/Simple.Data#187]
Using: ADOAdapter, SqlProvider, SQL Server 2008 database

Consider the following call where AlbumId is the PK for the Album table but 1 is not a valid AlbumId.

db.Albums.Get(1);

Currently this throws Microsoft.CSharp.RuntimeBinder.RuntimeBinderException : "Cannot perform runtime binding on a null reference".

Shouldn't this just return a null SimpleRecord and not throw an Exception?

**Comment by ThatRendle** [comment]
Ideally, the RuntimeBinderException should never be thrown. I'll be fixing
all these; thanks for tracking them down.
On May 6, 2012 10:28 PM, "Dan Maharry" <
reply@reply.github.com>
wrote:

**Comment by ThatRendle** [comment]
I can't reproduce this. This test passes:

```
[Test]
public void GetWithNonExistentPrimaryKeyShouldReturnNull()
{
    var db = DatabaseHelper.Open();
    var user = db.Users.Get(1138);
    Assert.IsNull(user);
}
```

That's running in the SqlTest project.

**Comment by hmobius** [comment]
Yeah - my bad. Looked at this again and found the fault at my end.
Sorry
