### ISSUE TITLE
Can't Update -- Even using your Example

### ISSUE THREAD

**Issue by Jaben** [ThatRendle/Simple.Data#19]
I'm attempting to update using your example code:

```
  var customer = db.Customers.FindByCustomerId(1);
  customer.Address = "Changed";
  db.Customers.Update(customer);
```

I just pulled the latest and am running against SQL Server DB. It's throwing an "Specified Method is not Supported" exception:

Simple.Data\Simple.Data.Ado\OptimizedDictionary`2.cs    Line: 202 

```
set { throw new NotSupportedException(); }
```

Thanks.

**Comment by ThatRendle** [comment]
Thank you for finding that, and also causing me to find out that there were no integration tests on the Update method!

Have just pushed fix, will be released soon.

**Comment by Jaben** [comment]
Thanks. Works good.
