### ISSUE TITLE
Multiword schema separated with dot returns column not found on mssql

### ISSUE THREAD

**Issue by kostaswonga** [ThatRendle/Simple.Data#190]
Hi,

I got a mssql 2008 database that has a schema with the following name: 
"my.schema"
I am trying to query the table "mytable" under that schema with the following ways:

Db["my.schema"].mytable.FindByColumnId(1);
Db["[my.schema]"].mytable.FindByColumnId(1);
Db["[my.schema].[mytable]"].FindByColumnId(1);
Db.my.schema.mytable.FindByColumnId(1);
Db.myschema.mytable.FindByColumnId(1);

Some of these ways throw back a "Column not found" exception.

Profiler shows that the query send to identify the columns specifies the table as follows..
"my.schema.mytable". If I rename the table name in this query to "[my.schema].[mytable]" and run the same query that simple data sent it returns the columns within the table.

Do I miss something?

Thanks,
Kostas

**Comment by ThatRendle** [comment]
The obvious question this raises is "who on earth thought putting a period in a schema name was a good idea?"

I will try and find some way of making this work, but in exchange, please smack your database designer ;)

**Comment by kostaswonga** [comment]
You are absolutely right Mark. Given that this specific case was an isolated incident we corrected it to a single-word schema with no dot. I am just skeptical of what will happen if i have to use simple.data in a database that is full of those :(

Again, your support is greatly appreciated.
