### ISSUE TITLE
Inconsistency between tables and stored procedures concerning schema prefix

### ISSUE THREAD

**Issue by rdewson** [ThatRendle/Simple.Data#192]
I notice it is possible to call a table without defining the schema. The code below is a demonstration of this

```
        var myDb = Database.OpenConnection("Data Source=.;Initial Catalog=Payments;Integrated Security=True");
        Database.TraceLevel = TraceLevel.Verbose;
        myDb.Applications.FindBy(ApplicationId: 1); // This works
        myDb.payment.Applications.FindBy(ApplicationId: 1); // This also works
```

However, you are unable to call a stored procedure without defining the schema. I guess calling the stored procedure is not prefixing it with the default schema? My default schema is "payment"

```
        myDb.payment.rdTestPayment(); // This works
        myDb.rdTestPayment();  // This doesnt
```

**Comment by ThatRendle** [comment]
Sorry that took so long, been busy.
