### ISSUE TITLE
Null DateTime returning as DateTime min (1/1/001)

### ISSUE THREAD

**Issue by geoffreysmith** [ThatRendle/Simple.Data#195]
Using 0.16.2.1 when I have a nullable DateTime property and the database field is set to null, I am return the default null value for DateTime instead of the default null value for DateTime? The problem lies in PropertySetterBuilder.cs, SafeConvertNullable, adding default(T?) allows it to work.

```
    internal static T? SafeConvertNullable<T>(object source)
        where T : struct 
    {
        if (ReferenceEquals(source, null)) return default(T?);
        return (T) source;
    }
```

The unit tests only test nullable DateTimes that have an actual value set. I have created a test where a nullable DateTime property is set to null, and the fix works.

I can submit a pull request, but I'm not quite sure if this is an actual fix or if I'm experiencing the correct behavior.

**Comment by codeprogression** [comment]
I am getting this as well. When I retrieve a record then try to save the updated record back, I get a invalid SqlDateTime error.

**Comment by npeeples** [comment]
I think this also follows for almost all other value types. I have a table that returns a INT NULL field, and I think that the property being set to `null` instead of `default(int)` (0) is proper. `default(T?)` correctly sets it to null as it does it for DateTime also.

**Comment by ghost** [comment]
I'm having the same issue here with all nullable types. This is new since I upgraded to 0.16.2.1 from 0.12.2.2. This is really a problem as the data being retrieved incorrectly gets saved as the wrong value.

**Comment by ThatRendle** [comment]
I am so sorry that this has taken so long to get a fix. It's been a manic couple of months.

**Comment by ghost** [comment]
Thanks, Mark! I am so grateful that you take the time to maintain this project. It cannot be easy to juggle it with real life.

**Comment by geoffreysmith** [comment]
Thanks Mark!

**Comment by codeprogression** [comment]
Thanks Mark! Hope the mania subsides a bit!
