### ISSUE TITLE
Add option of "with (nolock)" for queries

### ISSUE THREAD

**Issue by morganjohnston** [ThatRendle/Simple.Data#197]
For dealing with SQL Server pessimistic read deadlocks.

SELECT *
FROM table with (nolock)
where column = @blah

Some more details about the issue here: http://www.codinghorror.com/blog/2008/08/deadlocked.html

**Comment by kppullin** [comment]
Perhaps as a workaround, use a SqlTransaction with IsolationLevel.ReadUncommitted?   Do you require table level granularity?

**Comment by morganjohnston** [comment]
Hi, no I don't need table level granularity so this should work fine, thanks.

**Comment by morganjohnston** [comment]
...but how would I use a SqlTransaction with Simple.Data? SimpleTransaction doesn't seem to have a parameter to provide IsolationLevel...

**Comment by maniserowicz** [comment]
It does now, see issue #210 for details

**Comment by ThatRendle** [comment]
Closing this. "with nolock" is too DBMS-specific, transaction workaround is cross-DBMS.
