### ISSUE TITLE
Homogenized Column Names leads to duplicates

### ISSUE THREAD

**Issue by thejuan** [ThatRendle/Simple.Data#198]
I have a legacy schema that uses underscores as separators for column names i.e. Agent_Agreement.
I have a situation where once the underscores are removed (Column.HomogenizedName) there are duplicate columns in the table and the ColumnCollection.FindColumnWithName blows up (as it is using SingleOrDefault)

**Comment by ThatRendle** [comment]
You have column names which differ only by non-alphanumeric characters? That is honestly a situation I never expected.

**Comment by thejuan** [comment]
Neither did i, i have changed the regex via reflection for now.
In rare cases valid names overlap i.e.
its_how
IT_show

**Comment by ThatRendle** [comment]
Added a static HomogenizeEx.SetRegularExpression method so you won't need to use reflection. :)

**Comment by thejuan** [comment]
Thanks
