### ISSUE TITLE
FindAll

### ISSUE THREAD

**Issue by MortenL** [ThatRendle/Simple.Data#20]
Is FindAll broken?  FindAllBy works fine, and I can probably just create a FindAllById(db.myTable.Id > -1) or something like that.

**Comment by ThatRendle** [comment]
FindAll() is just All():

Database.Open().Customers.All()

-----Original Message-----
From: MortenL
Sent: 29 March 2011 12:49
To: mark@markrendle.net
Subject: [GitHub] FindAll [markrendle/Simple.Data GH-20]

Is FindAll broken?  FindAllBy works fine, and I can probably just create a FindAllById(db.myTable.Id > -1) or something like that.

## 

Reply to this email directly or view it on GitHub:
https://github.com/markrendle/Simple.Data/issues/20

**Comment by MortenL** [comment]
ah! cheers!
