### ISSUE TITLE
The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by jfollas** [ThatRendle/Simple.Data#200]
Not sure if this is by design, but if the Column name in an UpdateByxxx command does not match the case of the key in the provided key/value list, then an error would result.

The following will fail:

``` csharp
db.stagedEquipment.UpdateByProjectIDAndDateAndSubcontractorID(projectID: projectID, Date: date, SubcontractorID: subcontractorID, approved: true);
```

Note uppercase "P" in "ProjectID" in the command, but lowercase "p" in the key/value pair.  Changing to "ProjectID" in the key/value will work as expected.

**Comment by ThatRendle** [comment]
No, it's not by design. Sorry. Will fix in next release.

Mark

On Tue, Jun 12, 2012 at 3:30 PM, jfollas <
reply@reply.github.com
