### ISSUE TITLE
Find throws exception at different point in execution to FindAll

### ISSUE THREAD

**Issue by hmobius** [ThatRendle/Simple.Data#202]
Consider the following code

``` c#
try
{
  var db = Database.Open();
  var albums = dbQuery(db);
  if (albums == null)
  {
    Console.WriteLine("Query returned null");
    return;
  }

  Console.WriteLine("Query returned a {0}", albums.GetType().FullName);

  if (albums is SimpleRecord)
  {
    Console.WriteLine(albums.Title);
  }
  else
  {
    foreach (var album in albums)
    {
      Console.WriteLine(album.Title);
    }
  }
}
catch (Exception ex)
{
  ShowException(ex);
}
```

If line 4 is replaced by

```
var albums = db.Albums.Find(db.Albums.GenreId == "a")
```

a FormatException is thrown on this line as you step through code.
If line 4 is replaced by the FindAll equivalent...

```
var albums = db.Albums.FindAll(db.Albums.GenreId == "a")
```

the albums variable is assigned a SimpleQuery object and the FormatException is not thrown until the foreach loop tries to iterate through the SimpleQuery object and late binding occurs.

In a nutshell, Find appears to be evaluating the malformed SimpleExpression earlier than FindAll. I believe that FindAll should also throw the exception as Find does at the moment it is called rather than Simple.Data throwing it later on when late binding occurs. (And as it ties in with Issue 201, the FormatException thrown should be wrapped in a MalformedExpressionException.)

**Comment by ThatRendle** [comment]
The problem is that Simple.Data can't tell that that's wrong until it
tries to build the SQL using the DB schema, and it doesn't do that
until you enumerate the query.

Agree about the MalformedExpression exception, though.

Cheers,
Mark

Sent from my iPad

On 13 Jun 2012, at 12:23, Dan Maharry
reply@reply.github.com
wrote:
