### ISSUE TITLE
Bulk updates take place outside transaction

### ISSUE THREAD

**Issue by duncanbrown** [ThatRendle/Simple.Data#203]
Using the SqlServer adapter, bulk updates within a transaction are committed immediately, not when the transaction is committed.

Example:

Update of a single item:

``` C#
var db = Database.Open();
using (var trans = db.BeginTransaction())
{
    var thing = trans.Users.FindById(51);
    thing.UserName = "new name";                
    trans.Users.Update(thing);
}
```

As expected (because the transaction is not committed), no changes are made to the database after running this code.

Update of multiple items:

``` C#
var db = Database.Open();
using (var trans = db.BeginTransaction())
{
    var thing = trans.Users.FindById(51);
    thing.UserName = "new name";
    var list = new List<dynamic> { thing };
    trans.Users.Update(list);
}
```

Running this code persists the new user name, despite the transaction not having been committed.

**Comment by ThatRendle** [comment]
I'll get on that ASAP.
