### ISSUE TITLE
Select() runs All() by implication if query not specified

### ISSUE THREAD

**Issue by hmobius** [ThatRendle/Simple.Data#205]
Not sure if this counts as a bug or not... The purpose of Select in Simple.Data is to state which fields of data to retrieve from a data store. It qualifies one of the query commands - All, Find, FindBy, etc.- For example.

```
db.Albums.All().Select(
    db.Albums.AlbumId,
    db.Albums.Title);
```

So I was surprised to find that if I just called Select as below (i.e. as a query command rather than a qualifier), I got the same results as if I called All().Select as above.

```
db.Albums.Select(
    db.Albums.AlbumId,
    db.Albums.Title);
```

I was expecting Simple.Data to return a exception in the same way calling Where on its own throws an exception. For example.

```
db.Albums.Where(db.Albums.GenreId == 1);
```

This throws a RuntimeBinderException because it can't cast a FunctionReference to an IEnumerable.

**Comment by ThatRendle** [comment]
Yeah, the reason for this is that Select can be used as a prefix for Get or Find/FindBy. Regarding the inconsistency, I'm wondering about just letting Where work... what do you think?

**Comment by hmobius** [comment]
I may be thinking about this only in a RDBMS style, but SELECT \* is meant to retrieve data. You expect that. On the other hand, WHERE is just a clause of a SELECT statement and would throw an error if you executed it on its own in SQL Mgmt Studio. So why be counterintuitive and have where be the equivalent of All().Where(...) which is more intuitive to read and only six more characters to type?

Dan

---

Dan Maharry

about: http://about.me/danmaharry
twitter: http://www.twitter.com/hmobius

-----Original Message-----
