### ISSUE TITLE
MySql Schema Provider GetTables does not escape table names

### ISSUE THREAD

**Issue by christopherread** [ThatRendle/Simple.Data#208]
The MySql Schema Provider method FillColumnCache calls "SHOW COLUMNS FROM table;" for each table in the database. 

I am getting MySqlException because my database contains a table called `group`, which is a reserved word.

Simple fix would be to enclose table names in single quotes, e.g. SHOW COLUMNS FROM `group`;

**Comment by christopherread** [comment]
Realised this isn't actually the correct repository for Simple.Data.Mysql, apologies :)

I have attempted to patch it myself here:
https://github.com/Vidarls/Simple.Data.Mysql/pull/16

**Comment by richardhopton** [comment]
Thanks! I'll close this issue :-)

**Comment by ThatRendle** [comment]
Right, well, OK then. I'll go back to sleep :)
