### ISSUE TITLE
Setting IsolationLevel for transactions when using AdoAdapter

### ISSUE THREAD

**Issue by maniserowicz** [ThatRendle/Simple.Data#210]
It would be nice to be able to set IsolationLevel on transactions created by AdoAdapter. Started by question on google group: https://groups.google.com/d/topic/simpledata/qPVoP2epvLk/discussion .

**Comment by ThatRendle** [comment]
There is a release planned this week (which means "by Sunday") to wrap up all the current issues; I'll get this included in that.

**Comment by ThatRendle** [comment]
Right, done that. The code, that is. It'll be in 0.17.

**Comment by maniserowicz** [comment]
you are just awesome, man, thanks!
