### ISSUE TITLE
Setting command timeout

### ISSUE THREAD

**Issue by madness2222** [ThatRendle/Simple.Data#216]
Hi,

I'm using Simple.Data.SqlServer to access my MS SQL database. Is there any way I can set the command timeout on the query I'm executing on the database?

Many thanks.

**Comment by ThatRendle** [comment]
Sorry, this has come up before but never been raised as an issue, so thanks. I will address this by the final 1.0 release.

**Comment by madness2222** [comment]
Is there any way I can set the command timeout on the current stable release?

**Comment by ThatRendle** [comment]
Not at the moment, no. There's no access to the SqlCommand object from outside Simple.Data. Sorry.

**Comment by madness2222** [comment]
Just picking up on this again, Can you point out where about in the code I can hardwire the value for the command timeout? So, I can carry on working on my project until you've updated a parameter to specify the command timout in final 1.0 release.

**Comment by ThatRendle** [comment]
This is in the release I'm about to do (0.18 or 1.0-rc1).

**Comment by codereflection** [comment]
In case you want to know how to do this, you can use the WithOptions method off of your transaction, as the test in the following link shows:

https://github.com/markrendle/Simple.Data/blob/65ff01e482ce71190869001c221caa140feb70e5/Simple.Data.SqlTest/BulkInsertTest.cs#L43

Snippet:

```
            using (var tx = db.BeginTransaction())
            {
                tx.WithOptions(new AdoOptions(commandTimeout: 60000, fireTriggersOnBulkInserts: true));
```

**Comment by jjamsek** [comment]
You can also add the .WithOptions() when opening a named connection
Database.OpenNamedConnection("YourDB").WithOptions(new AdoOptions(3600));
