### ISSUE TITLE
Documentation errors

### ISSUE THREAD

**Issue by tcrosen** [ThatRendle/Simple.Data#217]
Hey there, thanks for this great library.  I'm really enjoying it, just noticed a few problems in the documentation which seem to be copy & paste errors, nonetheless they make it a bit confusing.

Here are some screenshots of the errors:

[Errors 1](http://i.imgur.com/55aGU.png)
[Errors 2](http://i.imgur.com/SRwFJ)

The descriptions are:
- Update actually returns the primary key of the row you updated, not the row.
- The @p3 params should actually be @p0 (the key) I think.
- A bunch of places say Insert instead of Update

I didn't see your docs anywhere in the source or I would've submit a pull request.  If I missed them let me know.
Thanks again.

**Comment by hmobius** [comment]
Thanks for spotting these. I haven't actually gotten to the Update docs yet save for copying across Mark's old blog posts, so good spot. The repo for the docs is at https://github.com/simplefx/simplefx.github.com. Please go ahead, fork, cahnge and request a pull.

**Comment by hmobius** [comment]
These have all been fixed now and the issue can be closed.

**Comment by ThatRendle** [comment]
Thank you.
