### ISSUE TITLE
Fails on retrieving sproc name when 2 sprocs exist with the same name but different schema

### ISSUE THREAD

**Issue by nickvane** [ThatRendle/Simple.Data#224]
When checking if the provided sproc name is a valid function it fails on SingleOrDefault() in the class ProcedureCollection as 2 items are in the list. This is because the sproc name given to the function doesn't have the schema name anymore.

this can be solved in Simple.Data.DynamicSchema by changing line 41 in method TryInvokeMember to

```
if (adapterWithFunctions != null && adapterWithFunctions.IsValidFunction(string.Format("{0}.{1}", _name, binder.Name)))
```

so that it gives the full sproc name.

**Comment by ThatRendle** [comment]
Fixed in 0.18.1 (1.0 RC2)
