### ISSUE TITLE
Provide a way to generate count(*) statements using Count()

### ISSUE THREAD

**Issue by hmobius** [ThatRendle/Simple.Data#226]
You can use GetCount() and GetCountBy() to generate `select count(*) from table` statements, but there doesn't seem to be a way to do this using `Count()`. For example, here are the ways I'd thought would achieve this.
1. Daisychain Count() onto the table in a Select() method.
   
   db.OrderDetails.All().Select(db.OrderDetails.Count());  
2. Daisychain Count() onto Star() or AllColumns() in a Select() method
   
   db.OrderDetails.All().Select(db.OrderDetails.Star().Count());  
3. Daisychain Count() onto the All() method
   
   db.OrderDetails.All().Count();  

All return exceptions

**Comment by ThatRendle** [comment]
Option 3 works now. The other two, not so much.
