### ISSUE TITLE
Magic casting a SimpleRecord to a Collection results in an empty Collection

### ISSUE THREAD

**Issue by hmobius** [ThatRendle/Simple.Data#229]
Magic casting a SimpleQuery to a Collection results in a collection with the same number of items in the collection as there are rows in the SimpleQuery. Magic casting a SimpleRecord to a Collection results in an empty Collection. I would have expected it to return either null, or a collection with one object in it so the following test passes.

``` [Test]
public void MagicCastSimpleRecordToOneItemCollection()
{
    List<Album> albumList = db.Albums.FindByGenreId(1);
    Assert.Equals(1, albumList.Count);
}
```

**Comment by ThatRendle** [comment]
Actually, that should throw an exception with a helpful message saying "I
think you meant FindAllBy".

I'll get to it at the weekend.

M

**Comment by ThatRendle** [comment]
Unfortunately, trying to be helpful at this point in the code incurs too much performance penalty.
