### ISSUE TITLE
Feature Request: Bulk Operations

### ISSUE THREAD

**Issue by Jaben** [ThatRendle/Simple.Data#23]
Thanks for all your hard work.

It's probably on your list... but just something like UpdateAll, DeleteAll and InsertAll.

Simple, I know, but cleaner than having to do a foreach over a list. Plus, could possibly bulk the SQL.

**Comment by ThatRendle** [comment]
Can certainly do UpdateAll and DeleteAll.

There's some work going on on a bulk insert/upsert feature which will return an IEnumerable of the inserted/updated records. It's a bit more complicated, but I really don't want to introduce features that I know are going to be deprecated very soon, so it'll be more of a wait for that. Hopefully 0.6.

**Comment by Jaben** [comment]
Cool, cool.
