### ISSUE TITLE
ToScalar needs consistent behaviour over SimpleRecord and SimpleQuery

### ISSUE THREAD

**Issue by hmobius** [ThatRendle/Simple.Data#230]
Call SimpleQuery.ToScalar(). It throws an exception unless SimpleQuery contains one item with only one property in it. 

Call SimpleRecord.ToScalar(). It just returns the scalar value for the first property.

Suggest : SimpleRecord.ToScalar() throws SimpleDataException if there are multiple properties in SimpleRecord like SQ.ToScalar().

**Comment by ThatRendle** [comment]
Agreed.

**Comment by ThatRendle** [comment]
I went the other way, and made SimpleQuery more forgiving. Introducing a new exception could break existing code. Also, the prescribed behaviour of IDbDataReader.ExecuteScalar is to return the first value of the first row and ignore everything else, which would seem a good design cue.
