### ISSUE TITLE
BadJoinExpressionException

### ISSUE THREAD

**Issue by hmobius** [ThatRendle/Simple.Data#232]
The Join, OuterJoin and LeftJoin methods all take two parameters, a target table reference and a JoinExpression of the form `targetTableKeyColumn: startTableKeyColumn`. For example, if Album and Genre are two tables linked by columns called AlbumId, the correct Join method would be

```
db.Albums.FindAllByGenreId(1)
      .Join(db.Genre, GenreId: db.Albums.GenreId)  ..etc
```

There are lots of ways to get this JoinExpression wrong. For example.

```
//  NullReferenceException
.Join(db.Albums, GenreId: db.Genre.GenreId) //tables round wrong way

// UnresolvableObjectException
.Join(db.Genre, NotPresent: db.Albums.GenreId)  // target table key column doesn't exist
.Join(db.Genre, GenreId: db.Albums.NotPresent)  // start table key column doesn't exist

// SqlException
.Join(db.Genre, GenreId: db.Albums.Title) // key columns don't match type
```

Would it be possible to create a `BadJoinExpressionException` type that is thrown when any of these cases occur which wraps the three Exception types listed above ad makes them available as InnerExceptions. This would match neatly the BadExpressionException type for SimpleExpressions.

**Comment by ThatRendle** [comment]
I've done this for the first one, but the second cases happen at execution time which makes them harder to catch. The improved message in UnresolvableObjectException should help, though.
