### ISSUE TITLE
Aliasing a boolean expression doesn't work anymore

### ISSUE THREAD

**Issue by sandord** [ThatRendle/Simple.Data#234]
I recently upgraded from Simple.Data.Core 0.16.2.1 to 0.18.1. I found that one of my queries broke due to the upgrade.

The exception is:

```
Simple.Data.SimpleExpression' does not contain a definition for 'As'
```

The following query pattern causes the exception, while it used to work in the aforementioned version:

```
.Select((db.TABLE.COLUMN == CONSTANT).As("ALIAS"))
```

**Comment by hmobius** [comment]
I don't understand. Why not use

.Select(db.Table.Column.As("Alias")).Where(db.Table.Column == Constant)

Surely that does the same thing?

**Comment by sandord** [comment]
That's not the same, I'm selecting the expression `COLUMN == CONSTANT` and I want the (boolean) result of the expression in the result column `ALIAS`. So I'm not looking to filter the result set using a `Where` clause.

**Comment by sandord** [comment]
By the way, I can't seem to get it to work (like it did) by downgrading Simple.Data to 0.16.2.1. Perhaps something else is causing this although I'm 100% sure the query didn't change since I last tested it successfully.

**Comment by ThatRendle** [comment]
Which database are you using?

**Comment by sandord** [comment]
I'm using SQL Server (2012).

**Comment by hmobius** [comment]
My mistake. According to http://stackoverflow.com/questions/497522/boolean-expressions-in-sql-select-list

select case when column = constant then 1 else 0 end as 'alias'
from table

is the way to do it in t-sql, but Simple.Data doesn't have a case statement yet to my knowledge.

**Comment by ThatRendle** [comment]
Closing as not supported.
