### ISSUE TITLE
Eager Loading a SimpleRecord - Different results depending on query command used

### ISSUE THREAD

**Issue by hmobius** [ThatRendle/Simple.Data#235]
I've been experimenting with eager-loading joins and noticed some difference in what happens when eager loading to a SimpleRecord. I'm using two tables. The Artists table has a 1:n foreign key relationship with the Albums table. Both use the artistId column. it is PK in the Artist table.

If I call db.Artists.FindAllByArtistId(22).WithAlbums().FirstOrDefault(); all works as expected. SimpleRecord returned with 14 items in Albums SimpleList. 

If I call db.Artists.Get(22).WithAlbums(); I get an Exception.

If I call db.Artists.WithAlbums().Get(22); A SimpleRecord is returned but with only 1 item in the Albums SimpleList. 

The SQL sent over is markedly different.

db.Artists.FindAllByArtistId(22).WithAlbums().FirstOrDefault();  sends the following

select 
  [dbo].[Artists].[ArtistId],[dbo].[Artists].[Name],
  [dbo].[Albums].[AlbumId] AS [__withn__Albums__AlbumId],
  [dbo].[Albums].[ArtistId] AS [__withn__Albums__ArtistId],
  [dbo].[Albums].[Title] AS [__withn__Albums__Title]
from [dbo].[Artists] 
LEFT JOIN [dbo].[Albums] ON ([dbo].[Artists].[ArtistId] = [dbo].[Albums].[ArtistId]) 
WHERE [dbo].[Artists].[ArtistId] = @p1
@p1 (Int32) = 22

db.Artists.WithAlbums().Get(22)  sends the following

WITH __Data AS (
  SELECT [dbo].[Artists].[ArtistId],[dbo].[Artists].[Name],
    [dbo].[Albums].[AlbumId] AS [__withn__Albums__AlbumId],
    [dbo].[Albums].[ArtistId] AS [__withn__Albums__ArtistId],
    [dbo].[Albums].[Title] AS [__withn__Albums__Title], 
    ROW_NUMBER() OVER(ORDER BY [dbo].[Artists].[ArtistId]) AS [_#_]
  from [dbo].[Artists] 
    LEFT JOIN [dbo].[Albums] ON ([dbo].[Artists].[ArtistId] = [dbo].[Albums].[ArtistId]) 
    WHERE [dbo].[Artists].[ArtistId] = @p1
)
SELECT [ArtistId],[Name],
  [__withn__Albums__AlbumId],
  [__withn__Albums__ArtistId],
  [__withn__Albums__Title]
FROM __Data WHERE [_#_] BETWEEN 1 AND 1
@p1 (Int32) = 22

I know that the recommended way to get a SimpleRecord is to FindAllBy().FirstOrDefault() , but Get and Find aren't deprecated and they both produce this wrong result.

**Comment by ThatRendle** [comment]
This is fixed now. The code that fixed it made my brain cry on the inside of my head. I hope you're happy.

**Comment by andagr** [comment]
The [documentation](http://simplefx.org/simpledata/docs/pages/Retrieve/LazyVsEagerLoading.htm) (under Eager Evaluation) still mentions this as a bug.
