### ISSUE TITLE
UpsertBy not inserting all data

### ISSUE THREAD

**Issue by JamesKyburz** [ThatRendle/Simple.Data#236]
When using UpsertBy the criteria keys are removed from the data when inserting.

Example

``` csharp
db.Staff.UpsertByUserId(UserId: 12, Email: "foo@foo.foo");
```

Insers a staff record with UserId null, this is because UserId is removed by :-

https://github.com/markrendle/Simple.Data/blob/master/Simple.Data/Commands/UpsertByCommand.cs#L65

**Comment by ThatRendle** [comment]
Closed thanks to pull request. Ta.
