### ISSUE TITLE
If input is a dictionary UpdateBy alters input

### ISSUE THREAD

**Issue by JamesKyburz** [ThatRendle/Simple.Data#239]
If the input to UpdateBy is a dictionary criteria keys are removed from the dictionary causing side affects.

https://github.com/JamesKyburz/Simple.Data/blob/master/Simple.Data/Commands/UpdateByCommand.cs#L59

Example

``` csharp
var user = new Dictionary<string, object>() {
  {"Id", 0},
  {"Age", 1},
  {"Name", "X"},
  {"Password", "P"}
};
user["Id"] = db.Insert(user).Id;
db.UpdateByName(user);
// Now user["Name"] does not exist;
```

**Comment by ThatRendle** [comment]
Just fixed, pulling your pull request on the other issue.

**Comment by JamesKyburz** [comment]
Brilliant!

I just wrote a failing test for issue 239, just in case it's any use :)

```
    [Test]
    public void TestUpdateByInputIsNotMutated()
    {
        var db = DatabaseHelper.Open();
        var user = new Dictionary<string, object>() {
          {"Id", 0},
          {"Age", 1},
          {"Name", "X"},
          {"Password", "P"}
        };

        user["Id"] = db.Users.Insert(user).Id;

        db.Users.UpdateById(user);

        Assert.AreEqual(4, user.Keys.Count);
    }
```

James Kyburz
Cell: +46 734 448489 | Google Talk: james.kyburz | Skype: james.kyburz
http://twitter.com/jameskyburz

**Comment by ThatRendle** [comment]
I was halfway through writing the test, you saved me a job. Thanks.
