### ISSUE TITLE
Feature Request: Add Generation Logging/Debugging Options

### ISSUE THREAD

**Issue by Jaben** [ThatRendle/Simple.Data#24]
Insert isn't working for me. Not sure why. Had to put some Debug.WriteLine() type of code in the command execute just to see what kind of code it was generating. I realize that Mock Database does that, but another option for when you need to see what's being run would be helpful.

Thanks.

**Comment by Jaben** [comment]
Better yet -- at a hook or event somewhere for generated SQL.

**Comment by ThatRendle** [comment]
That's something I've been meaning to do for ages. Just added it. All ADO command executions are written to the Trace with the category Simple.Data.Ado, including CommandType, CommandText and all parameters with values.

**Comment by Jaben** [comment]
Perfect. Thanks again. :)
