### ISSUE TITLE
Help using multiple schemas with Simple.Data.Oracle

### ISSUE THREAD

**Issue by sooey** [ThatRendle/Simple.Data#240]
Currently I'm using the appsetting in my config below to access the needed schema in oracle:

 key="Simple.Data.Oracle.Schema" value="XYZ"

This works for a single schema but I need to query data in a single oracle database but across many schema's.   How do I do this?

FYI - I've tried db.schema-name.table-name.FindBy... but this only works when my schema-name matches the one set in my config.  I've also removed the config setting and tried the syntax above with no success.

**Comment by ThatRendle** [comment]
This sounds like an issue with the Oracle provider. Try https://github.com/flq/Simple.Data.Oracle/issues
