### ISSUE TITLE
Unable to convert complex object containing iList<string>

### ISSUE THREAD

**Issue by andycwk** [ThatRendle/Simple.Data#243]
I have a domain object MyObject {string Name {get; set;}  iList<string> Paths{get; set;} }

In the db I have a table MyObject that contains an id and name columns, and a table Paths containing myObjectId and Path columns.

Running 
var myObjects = Database.Default.MyObjects.All().WithPaths().ToList<MyObject>();

Caused 
Cannot implicitly convert type 'Simple.Data.SimpleRecord' to 'xxx.xxx.Models.MyObject'

I'm not sure if this is a fault, but can you shine any light on the issue - is what I'm expecting to happen valid?

**Comment by ThatRendle** [comment]
Does MyObject have a default (i.e. parameterless) constructor?

Oh, and it won't be able to map from the Path table to a string, you'd need a proper MyPath type with a Path property.

I can think of behaviour that might work there, but it will be a while before I get a chance to implement it.

**Comment by andycwk** [comment]
Ah that might explain it :(

It's not shown in my object definition but I should have wrote iList<string> Paths.

I was starting to wonder if I needed a complex type for the path (and at the same time hoping not) instead of a string... oh well..

Thanks for the assistance.
