### ISSUE TITLE
Distinct with Take

### ISSUE THREAD

**Issue by jfollas** [ThatRendle/Simple.Data#244]
@markrendle AH... Bug alert! I had a .Take(50) on there. Emitted SQL was SELECT TOP 50 DISTINCT... Needs to be SELECT DISTINCT TOP 50... 

My order of operations looks something like:

db.Table.All().Where(...).Distinct().Select(...).Take(50);

**Comment by richardhopton** [comment]
This is fixed now for SQL Server (and SQL CE)
