### ISSUE TITLE
Documentation for HomogenizeEx.SetRegularExpression

### ISSUE THREAD

**Issue by codereflection** [ThatRendle/Simple.Data#247]
I sort of fell upon `HomogenizeEx.SetRegularExpression` when I needed to change the regular expression to include underscores, but it took me a long time to find the feature.  It would be awesome to have this in the documentation.  I would have submitted a pull request, but it doesn't appear that the documentation is part of this repo, or at least I'm too blind to see it. :)

https://github.com/markrendle/Simple.Data/blob/master/Simple.Data/Extensions/HomogenizeEx.cs#L33

**Comment by ThatRendle** [comment]
Sorry about that.

The docs are part of the SimpleFx site project, which is here: https://github.com/simplefx/simplefx.github.com

I'm sure a pull request would be much appreciated.

**Comment by codereflection** [comment]
Done and done.

[Pull request](https://github.com/simplefx/simplefx.github.com/pull/24)
