### ISSUE TITLE
Compatibility Issues Simple.Data.Mysql 18.0.0

### ISSUE THREAD

**Issue by alrcastro** [ThatRendle/Simple.Data#248]
Just to let you guys now that when I use Simple.Data.Mysql Version 18.0 with the ADO/Core 18.3 I get this error when I try to open a connection:

{System.TypeLoadException: Method ApplyPaging of type Simple.Data.Mysql.Mysql40.MysqlQueryPager do assembly Simple.Data.Mysql.Mysql40, Version=0.18.0.0, Culture=neutral, PublicKeyToken=null does not have an implementation.}

Anyway, I had to install the Core and Ado version 18.0 to make it work.

Thanks,

**Comment by ThatRendle** [comment]
Hi,

There was a breaking change in one of the interfaces which requires provider authors to update their code. I have submitted a pull request to the MySQL project with the necessary change.

M

**Comment by ThatRendle** [comment]
I see that vidarls has released 0.18.3, so this should be fixed now.
