### ISSUE TITLE
Issue: Insert(dynamic) needs more options

### ISSUE THREAD

**Issue by Jaben** [ThatRendle/Simple.Data#25]
In DynamicTable.cs Insert(dynamic) -- it wasn't working with my statically typed object. I modified with the following code:

```
var dictionary = entity as IDictionary<string, object> ?? ObjectEx.ObjectToDictionary((object)entity);

if (dictionary != null)
{
  _dataStrategy.Insert(_tableName, dictionary);
}
```

Thanks.

**Comment by Jaben** [comment]
Excuse my lack of a pull request... still learning GIT :)

**Comment by Jaben** [comment]
Should be returning the Identity?

**Comment by Jaben** [comment]
My modified function:

```
public dynamic Insert(dynamic entity)
    {
        var dictionary = entity as IDictionary<string, object> ?? ObjectEx.ObjectToDictionary((object)entity);

    return dictionary != null ? this._dataStrategy.Insert(this._tableName, dictionary) : null;
    }
```

**Comment by ThatRendle** [comment]
Actually, the Insert should be handled by the dynamic resolution, and that method shouldn't even be in the DynamicTable class. Good catch; I've removed the method now.

**Comment by Jaben** [comment]
Thanks Mark... Yeah, deleting that fixed everything. And I see now it returns that SimpleRecord.
