### ISSUE TITLE
SQLite adapter only works when file suffix is ".db"

### ISSUE THREAD

**Issue by bmiller1** [ThatRendle/Simple.Data#253]
I get the dreaded "No ADO Provider found" error when attempting to access a SQLite database whose file suffix is anything other than ".db".  

For example "myDatabase.s3db" does not work.  Rename the file to "myDatabase.db" and it works fine.

I am using the Simple.Data.Database.OpenFile method to open the database.

**Comment by ThatRendle** [comment]
The SQLite provider is a separate project, you can raise an issue for it at: https://github.com/NotMyself/Simple.Data.Sqlite
