### ISSUE TITLE
Update with NULL value doesn't update

### ISSUE THREAD

**Issue by ThatRendle** [ThatRendle/Simple.Data#26]
Setting a property to NULL and then calling Update doesn't set that value to NULL in the database.

**Comment by EricRohlfs** [comment]
I am having the same issue, the strings in my poco classes are null when the default constructor is called.  As a test I set all the string properties to string.empty and everything worked.  But I don't want to have to do  that for all my poco classes.

**Comment by ThatRendle** [comment]
Fix for this is in Github, will be in next Nuget release.

**Comment by flq** [comment]
I guess this can be closed?

**Comment by ThatRendle** [comment]
Yup. :)
