### ISSUE TITLE
db.TableName.OrderByFieldName() works but shouldn't

### ISSUE THREAD

**Issue by hmobius** [ThatRendle/Simple.Data#269]
If I call OrderBy() directly on a table reference without a base command (All, FindAll etc), I'd expect a NullReferenceException to be thrown because there's no command to qualify. This works if I call any of the following

```
db.Albums.OrderBy();
db.Albums.OrderBy(db.Albums.ArtistId);
db.Albums.OrderBy(db["Albums"]["ArtistId"]);
```

But if I call 

```
db.Albums.OrderByArtistId();
```

The albums table is returned ordered by artistId. I'd expect this last call not to run.

**Comment by ThatRendle** [comment]
Too hard to fix.
