### ISSUE TITLE
OrderBy can be used to order by two or more columns

### ISSUE THREAD

**Issue by hmobius** [ThatRendle/Simple.Data#272]
We should use ThenBy() to state a second column but it appears to be able to use OrderBy to do the same in one instance. 

I'd expect an ArgumentException to be called in the first two cases and then perhaps an InvalidOperationException to be thrown in the third?

```
// Throws UnresolvableObjectException - Column not found
db.Albums.All().OrderByArtistIdAndTitle();     
// Throws NullReferenceException
db.Albums.All().OrderBy(db.Albums.ArtistId, db.Albums.Title);              
// Runs All.OrderBy(ArtistId, Title)
db.Albums.All().OrderBy(db.Albums.ArtistId).OrderBy(db.Albums.Title);             
```

**Comment by ThatRendle** [comment]
Can't fix first case.
Second case now actually works.
