### ISSUE TITLE
Add CUBRID Database support

### ISSUE THREAD

**Issue by kadishmal** [ThatRendle/Simple.Data#274]
Simple.Data supports a bunch of relational databases. Why not [CUBRID](http://www.cubrid.org) then? It provides over 90% SQL compatibility with MySQL and has [ADO.NET provider](http://www.cubrid.org/wiki_apis/entry/cubrid-ado-net-driver) which provides 100% full-managed .NET code. Worth looking.

**Comment by ThatRendle** [comment]
Hi, thanks for the suggestion. Simple.Data is designed as an extensible base library, and in the core project I only maintain the ADO.NET providers for SQL Server and SQL Server Compact. All other databases are supported by other people. Maybe you could clone the Simple.Data.MySQL repository (https://github.com/Vidarls/Simple.Data.Mysql) and use it as a basis for a CUBRID provider? I think it's got a pretty comprehensive test suite, so if you could get them all passing against CUBRID you'd be pretty much done.
