### ISSUE TITLE
ThenBy ignores column named parameter in favour of fluid style name.

### ISSUE THREAD

**Issue by hmobius** [ThatRendle/Simple.Data#280]
If I call ThenByColumnName(xyz) where xyz is anything, xyz is ignored and the query sorted.

```
db.Albums.All().OrderBy(db.Albums.AlbumId).ThenByGenreId(1);
db.Albums.All().OrderBy(db.Albums.AlbumId).ThenByGenreId(db.Albums.Title)
```

In the two calls above, results are sorted on AlbumId and GenreId. I would expect an ArgumentException to be thrown instead.

**Comment by ThatRendle** [comment]
Fixed
