### ISSUE TITLE
Length function throws ambiguous exception when you pass it an argument

### ISSUE THREAD

**Issue by hmobius** [ThatRendle/Simple.Data#290]
The Length function does not take any arguments. But when you pass it one - for example

   var albums = Database.Open().Albums.Select(db.Albums.Title.Length(123));

you get the following exception.

```
Query returned a Simple.Data.SimpleQuery
Simple.Data.Ado.AdoAdapterException
The len function requires 1 argument(s).
```

The message is wrong for two reasons : its the Length function and it requires 0 arguments.
It should also be throwing an ArgumentException.

**Comment by ThatRendle** [comment]
Unfortunately that's just wrapping a SqlException and I'm limited as to what I can do.
