### ISSUE TITLE
Opening OData source gives Unrecognized type Edm.GeographyPoint

### ISSUE THREAD

**Issue by peterodk** [ThatRendle/Simple.Data#294]
When opening this datasource the error "Unrecognized type Edm.GeographyPoint" is thrown.

url="http://services.odata.org/V3/OData/OData.svc/";
dynamic db = Database.Opener.Open(url);
table="Products";
 IEnumerable<dynamic> data= db[table].All();

**Comment by ThatRendle** [comment]
Please repost this issue to https://github.com/simplefx/Simple.OData/issues
