### ISSUE TITLE
Does Simple.Data support Union?

### ISSUE THREAD

**Issue by nripendra** [ThatRendle/Simple.Data#300]
It seems simple.data supports joins but doesn't support unions, or am I missing something?

**Comment by ThatRendle** [comment]
No, unions are not currently supported.

_Mark Rendle_
_Founder & CEO_
_Oort Corporation_
_Makers of_ _Zudio_ https://zud.io/

**Comment by nripendra** [comment]
Thanks for clarifying, Mark.
