### ISSUE TITLE
Paging views

### ISSUE THREAD

**Issue by maniserowicz** [ThatRendle/Simple.Data#308]
Currently views cannot be paged using Simple.Data because they do not have primary keys.
The problem is that keys are really necessary in the SqlQueryPager. Even SqlCe40QueryPager that comes with Simple.Data does not require them. MySql pager would ignore the keys too. And our PostgreSQL pager (found here, forked from the "official" one that seems to be abandoned: https://github.com/ultrico/Simple.Data.PostgreSql ) does not need them either.
Wouldn't it be a good idea to allow paging on tables/views without primary key and move this exception from AdoAdapterQueryRunner to SqlQueryPager ?

https://github.com/markrendle/Simple.Data/blob/master/Simple.Data.Ado/AdoAdapterQueryRunner.cs#L188

**Comment by MattBecker** [comment]
If I understand the pull request properly, this was only applied to the v2.0.0-alpha1 branch, and not Simple.Data.Core 1.0.0-rc3.  Is that correct?
