### ISSUE TITLE
Select values into nullable type

### ISSUE THREAD

**Issue by anoop-kv** [ThatRendle/Simple.Data#334]
Hi,

I have a integer column in the database which is nullable. So while creating the datamodel i made the property "int?". This way my insert/update statement is working as expected. 

However when I try to select data from the table into the same datamodel, the field is not getting populated. What am i doing wrong ? Can somebody please suggest ?

**Comment by WayneHiller** [comment]
That should not be a problem I do it all the time. Do you have public get & set on the property in the data model

**Comment by ThatRendle** [comment]
This should work. Which database are you using?

On Tuesday, 4 March 2014, anoopkv2000 notifications@github.com wrote:

> Hi,
> 
> I have a integer column in the database which is nullable. So while
> creating the datamodel i made the property "int?". This way my
> insert/update statement is working as expected.
> 
> However when I try to select data from the table into the same datamodel,
> the field is not getting populated. What am i doing wrong ? Can somebody
> please suggest ?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/markrendle/Simple.Data/issues/334
> .

## 

_Mark Rendle_
_Founder & CEO_
_Oort Corporation_
_Makers of_ _Zudio_ https://zud.io/

**Comment by anoop-kv** [comment]
I am using Oracle. And yes this is a public property in my model

**Comment by WayneHiller** [comment]
I have not tried it in oracle. Is it a normal column name with no special characters?

**Comment by anoop-kv** [comment]
Sorry, I made a mistake. The database column was in fact "VARCHAR". So I have changed the model property to String, and things are now working fine. Thanks for the pointer.
