### ISSUE TITLE
Explicit joins

### ISSUE THREAD

**Issue by ThatRendle** [ThatRendle/Simple.Data#37]
Join(db.Y, db.X.yid == db.Y.id)

**Comment by richardhopton** [comment]
Is this now supported like this?

Join(db.Y).On(db.X.yid == db.Y.id)

**Comment by ThatRendle** [comment]
Yup.

Sent from my iPad (until Win8 gets a mail app)

On 24 Nov 2011, at 21:25, richardhopton
reply@reply.github.com
wrote:
