### ISSUE TITLE
Aliasing

### ISSUE THREAD

**Issue by ThatRendle** [ThatRendle/Simple.Data#38]
.As(str) on columns and tables

**Comment by flq** [comment]
The question on this feature to me is what it is aiming at. Is it to allow properties on DTOs to be called differently? If that's the case I would like to propose a slightly different approach(or mabe as an addition) - The ability to dictate which conversions between DB columns and DTO properties' names are OK. Often on DB schemas one deals with abbreviations (CY is Country and stuff like that). It would be cool if one could say "whenever a column contains CY, it can map to the word Country on the DTO (as one scenario)

**Comment by ThatRendle** [comment]
Aliasing is for changing the names of fields in a result set, and for table aliases in queries to allow the same table to be referenced more than once. What you're talking about seems to fit into your mapping idea, yes?

**Comment by flq** [comment]
It kinda fits in, in that configuration could look quite similar and they would act globally. While the converters could convert values, the renamers could change "funny" db names (like on legacy schemas) to more meaningful stuff. I can see the value of the way of aliasing you propose now...maybe we can aim for both? :)

**Comment by ThatRendle** [comment]
It pushes towards more ORM functionality, which I'm a bit wary of. If we could implement these things as plug-ins in some way, then I'd be much happier.

**Comment by flq** [comment]
I understand you don't want to build yet another ORM, but I'd think that it would be in the spirit of SimpleData, considering that the db and its schema is the master. Either way, pluggability would certainly be a very good and lovely thing to have, but probably a bit tougher in terms of effort.

**Comment by flq** [comment]
That plug-in statement of yours was wallowing through my brain. My interim conclusion is that some refactoring of the not too lightweight sort may be required to pull that off. So, for now I'm opting to just do the data conversion stuff, and maybe at a later date if all involved parties feel brave enough make the complete dynamic objects pipeline pluggable. That way new words/functionality may be introduced at all levels of a query / command.
