### ISSUE TITLE
Issue when persisting an instance

### ISSUE THREAD

**Issue by tt** [ThatRendle/Simple.Data#5]
I have defined this entity:

```
public class Post
{
  public int Id { get; protected set; }
  public string Slug { get; set; }
  public string Text { get; set; }
}
```

If I insert into the database with `db.Posts.Insert(Slug: "foo", Text: "Bar")` is everything handled correct. If I on the other hand create `new Post { Slug = "foo", Text = "bar" }` and passes it to the method, the slug column in the database is set to `0`, and the text column is set to `foo`. The `bar` value is not persisted anywhere.

**Comment by ThatRendle** [comment]
Fixed in 0.4.5; new tests added for this case.
