### ISSUE TITLE
Conversion capabilities between .NET and DB values

### ISSUE THREAD

**Issue by flq** [ThatRendle/Simple.Data#50]
Introduce converter functions which you can attach to columns. Syntax-wise it could look something like this:

```
var converterPlugin = new ConverterPlugin();
converterPlugin.Add(_db.Customers.Id, g => g.ToByteArray(), v => new Guid((byte[])v));
converterPlugin.Add(col=>col.Name.EndsWith("BOOL"), BoolToDb, DbToBool);

DatabaseOpener.Profiles.Add(cfg=> {
  cfg.Name = "ORCL";
  cfg.Connectionstring("...");
  cfg.AddPlugin(converterPlugin);
});

_db = Database.OpenProfile().ORCL;
```

Converters are applied when searching/updating inserting in that a provided .NET value passes through a converter, or when reading back values in that the DB value is converted to some .NET type.

It should have support for a single column definition, or a definition that defines a predicate that checks whether a given column should get the converters applied. That way one can do conversions for e.g. a specific column data type or based on some column naming convention. 

This feature is based on the ideas put down in #56

**Comment by DaveSussman** [comment]
This is definitely something I'd be interested in. I have char columns in a database that need to be surfaced as byte and byte[] in the objects. I haven't tried it with the database yet, but using the XmlMockAdapter I get conversion errors (cannot convert string to System.Byte[]).

**Comment by richardhopton** [comment]
I've got a legacy database that stores booleans as CHAR(1) with Y or N - having a feature like this would be helpful.

**Comment by ThatRendle** [comment]
This keeps coming up, so I'm going to pull it into v1.0, for a 0.17 pre-release. Spiking ideas at the moment.

**Comment by hmobius** [comment]
A quick ping on this issue - is it still on for v1.0? The roadmap I found suggests you've targeted it for v1.1

**Comment by ThatRendle** [comment]
I was planning on putting it into 1.1 so that the gap between the
software and the docs didn't keep growing on you. I'll probably start
releasing 1.1.x-beta soon when I get to that stuff.

Sent from my iPad

On 13 Jun 2012, at 12:26, Dan Maharry
reply@reply.github.com
wrote:

**Comment by JohannesHoppe** [comment]
I vote for that feature, too! :-)

**Comment by flq** [comment]
I have something of a feeling that Simple.Data is quite simply not going anywhere, so I'll gracefully close this issue. Nothing to see here, move along.

**Comment by jdscolam** [comment]
:'(
