### ISSUE TITLE
Be more tolerant of what properties DTOs have defined

### ISSUE THREAD

**Issue by flq** [ThatRendle/Simple.Data#52]
I got a call today from one of our tems that are using Simple.Data. He said that he had a special property on his DTO and SiD would try to persist the column and complain that it doesn't exist. 

I was wondering - what if the column set drives what gets persisted and any extra properties on a DTO gets ignored?

**Comment by ThatRendle** [comment]
I thought the column set did drive it. That's certainly the sensible way to do it. I'll have a look at that in a bit.

**Comment by ThatRendle** [comment]
No, I was wrong. What an absolute shocker of an omission, which I have now fixed. I'm also filtering the data keys/values that get passed through to ICustomInserter, so you don't have to duplicate the check.
