### ISSUE TITLE
Definition of "Database Profiles", introduction of 2 extension points

### ISSUE THREAD

**Issue by flq** [ThatRendle/Simple.Data#56]
Hi Mark,
 I would like to put a few thoughts down, see if it's something you like.
I was thinking of how a user could add more "meta"information to some kind of connection and one ide would be to allow connection profiles to be defined. A connection profile would be similar to a named connection. To define a profile one would access the "DatabaseOpener" and call "CreateProfile". The caller needs to specify 
- a profile name  (or the any option, which would apply any provisions of "stuff" to any connection obtained)
- a connect string, or how to obtain one
- add implementation of existing plugin interfaces.

This introduces a new way to get the dynamic db, namely via `DatabaseOpener.Profiles.ProfileName() : dynamic`.

Internally, Simple.Data would get a small container which contains any plugin interface implementations that come in via a profile

In order to cover issue #50 , we could introduce two interfaces, one specific to ado, which is allowed to inspect IDbCommand instances created by Simple.Data to interact with a db.

```
interface IAdoCommandPlugin {
  void Inspect(IDbCommand cmd);
}
```

The other hook is to inspect and possibly modify the `IDictionary<string,object>` returned by a call to the data store:

```
interface IDataStoreReturnPlugin {
  IDictionary<string,object> Inspect(IDictionary<string,object> values);
}
```

Now, this would allow extension of Simple.Data without pushing more features into the core.

**Comment by flq** [comment]
Um, I have the feeling that I can close this issue

**Comment by jdscolam** [comment]
:'(
