### ISSUE TITLE
Between statement 

### ISSUE THREAD

**Issue by Ulriksen** [ThatRendle/Simple.Data#6]
Version 0.45 seems to be incorrect when it comes to between statements as a result of the Range extension. 

In Simple.Data.Ado.ExpressionFormatter the FormatRange will output parantheses around the values, which will cause an execption when the sql statement is executed. 

Verified on Sql Server express 2008, SQL server CE 4.0 and Sql server 2005.

**Comment by ThatRendle** [comment]
Thanks for finding this, I'll fix it in 0.4.6, next couple of days.

**Comment by Ulriksen** [comment]
You might want to add a datetime specific version of the to extension method as well. Date parsing is a source of strange errors. 

 public static IRange to(this DateTime startDate, DateTime endDate)
        {
            return new Range<DateTime>(startDate, endDate);
        }

**Comment by ThatRendle** [comment]
There's an extension method on IComparable of T which will work with DateTime.

**Comment by ThatRendle** [comment]
Fixed, 0.4.6 now on NuGet.
