### ISSUE TITLE
Please Publish TestHelper to NuGet

### ISSUE THREAD

**Issue by NotMyself** [ThatRendle/Simple.Data#60]
Hi Mark,

I finally got around to updating my provider to support the latest version of Simple.Data. I had to hand build the TestHelper lib in order to use the extensions you created to give me access to the connection. It would be nice if you published this to nuget as well. 

Thanks,
Bobby

**Comment by ThatRendle** [comment]
Hi Bobby,

I made a couple of things public that were previously internal which should negate the need for TestHelper.

Try this:

var db = Database.Open(); // or whatever you're using for in-memory
var ado = db.GetAdapter() as AdoAdapter; // GetAdapter is now public
IDbConnection connection = ado.ConnectionProvider.CreateConnection(); // SQLite Provider should return persistent in-memory connection?

If any of that doesn't work, it's a bug and I'll fix it in the next couple of days.

Cheers,
Mark

**Comment by NotMyself** [comment]
That will work, we going to see a 6.8 soon?

**Comment by ThatRendle** [comment]
That's already in 0.6.7 :)

0.6.8 should happen this week, with explicit join support and a couple of fixes. Then there'll be a version bump to 0.9, which will be RC, and then 1.0, hopefully in July!

Cheers,
Mark

-----Original Message-----

**Comment by NotMyself** [comment]
sounds good!

**Comment by ThatRendle** [comment]
Assuming the making-things-public change has resolved this issue.
