### ISSUE TITLE
Nested Object Aliases

### ISSUE THREAD

**Issue by craiggwilson** [ThatRendle/Simple.Data#66]
Mark,
  I was adding alias support into the mongodb adapter and hit a snag.  It all works great until I need to alias a nested object and it's descendents.  For example, given the structure that users have an address, the following is the syntax I would need.

original shape:

```
usrs:
    adr:
        cty
        st
```

select portion of Query()

```
.Select(db.usrs.adr.As("Address")
    .Select(db.usrs.adr.cty.As("City"), db.usrs.adr.st.As("State"))
```

aliases shape:

```
usrs:
    Address:
        City
        State
```

I was going to add a Select statement onto ObjectReference and let the ObjectReference hold it's childrens selections, but wasn't sure if there were any problems that would cause.  If that seems ok, I'll do the work and send a pull request.  If you can think of another way, please let me know.

**Comment by ThatRendle** [comment]
I'm thinking about how this could apply to RDBMS data stores; there might be a syntax which would represent an "eager fetch" for detail collections.

How about lifting the Select method up into the main query, and changing the name to "With"? So your example would look like:

db.usrs.All()
   .With(db.usrs.adr.As("Address").Select(db.usrs.adr.cty.As("City"), db.usrs.adr.st.As("State")));

Without the nested select, in a SQL database, you would be able to do something like:

db.Posts.FindAllByDate(DateTime.Today).With(db.Posts.Comments);

Which would be a really useful syntax, I think.

**Comment by craiggwilson** [comment]
I think that is a great idea.  For RDMBS', that allows you to support lazy loading as you mentioned.  For a document database like mongodb, the semantics are different, but the syntax stays the same.  I like it a lot.

The one thing to remember for a document database is that there could be nested With statements.  With(db.usrs.adr.As("address").With(db.users.adr.geo.As("GeoCode").Select(etc...

Anyways, let me know what I can do to help...

**Comment by ThatRendle** [comment]
OK, this is going to be the main feature for 0.12.

**Comment by ThatRendle** [comment]
The new With clause in 0.14 should work for this, e.g.:

db.Orders.With(db.Orders.OrderItems.As("Items");

Let me know if there's a more elegant syntax you would like to see.
