### ISSUE TITLE
MultiQueries

### ISSUE THREAD

**Issue by maniserowicz** [ThatRendle/Simple.Data#68]
Hi,
It would be nice to be able to execute multiple queries in one db-hit. Something like NHibernate's "futures" - store all queries marked as futures and execute them together, returning multiple results.
The most obvious example is paging: execute count(*) along with the actual retrieval query together, both returned in a 2-element result set.

**Comment by ThatRendle** [comment]
I've got some ideas around this, watch this space.

**Comment by ThatRendle** [comment]
The paging-specific aspect of this issue has been handled with the WithTotalCount(out Promise<int> count) clause on SimpleQuery. Batched operations are still road-mapped.

**Comment by maniserowicz** [comment]
Yeah i saw your blog post, great job!
