### ISSUE TITLE
Connection closed error throwing on _.reader.Read()

### ISSUE THREAD

**Issue by geoffreysmith** [ThatRendle/Simple.Data#70]
I've just updated from the 2011-07-18 branch, before "Fixed enumerators and added observables." and I'm getting an error when trying to retrieve data. If I revert to the 07-18 branch everything works fine. Should I be accessing my data differently? Here's my DatabaseFactory:

```
public static class DatabaseFactory
{
    private static readonly object LockObject = new object();
    private static string connectionName;
    private static Database database;

    public static void SetConnectionName(string name)
    {
        connectionName = name;
    }

    public static dynamic GetDatabase()
    {
        if (database == null)
        {
            lock (LockObject)
            {
                if (database == null)
                {
                    database = Database.OpenNamedConnection(connectionName);
                }
            }
        }

        return database;
    }
}
```

In my method:

```
        var db = DatabaseFactory.GetDatabase();
        var viewModels = db.Categories.All().Cast<CategoryListViewModel>() as IEnumerable<CategoryListViewModel>;
```

Once I call execute viewModels (e.g., throw ToList on it), it will bonk out and say the database connection is closed. If I take out the cast, and just look at the dynamic model, it'll correctly show me what was returned from the database. I was having no problems with this before.

It seems like the BufferedEnumerables (which you took out) is causing the problem, but I'm unsure why. Any ideas?

**Comment by geoffreysmith** [comment]
I should say you did not take out bufferedEnumerables, you just renamed it and refactored it, but something in that refactoring is causing the read to bonk. I'm guessing the following code:

```
if (connection.State == ConnectionState.Closed)
             connection.Open();
```

But the fact that no one else is complaining makes me think I'm doing something not right.

**Comment by ThatRendle** [comment]
I've encountered a couple of issues with connections being closed by the database enumerator in my copy of the code, but I think I've caught and killed them all now. I've added a test which is pretty much the same as your code and it passes. Can you grab a copy of my latest trunk (https://github.com/markrendle/Simple.Data/commit/9531d3258467de20f986a646aa0a4fea094cd144) and see if you still get the problem?

**Comment by geoffreysmith** [comment]
Yeah I'm on the latest build, finally got it to work by matching your test:

IList<CategoryListViewModel> viewModels = db.Categories.All().ToList<CategoryListViewModel>();

For whatever reason the syntax I use doesn't work anymore. I will add this to the wiki.

**Comment by geoffreysmith** [comment]
Damn GitHub:

```
       IList<CategoryListViewModel> viewModels = db.Categories.All().ToList<CategoryListViewModel>();
```
