### ISSUE TITLE
InvalidOperationException when trying to iterate over a result that includes WithTotalCount

### ISSUE THREAD

**Issue by Vidarls** [ThatRendle/Simple.Data#74]
I can't post the code here as it's IP of my employer, and I have not had the time yet to recreate with more generic code.
But here is the stacktrace at least:
Message:
System.InvalidOperationException : Sequence contains more than one element

Stack trace
at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source) in 
at Simple.Data.Ado.QueryBuilder.SetQueryContext(SimpleQuery query) in 
at Simple.Data.Ado.QueryBuilder.Build(SimpleQuery query, IEnumerable`1& unhandledClauses) in 
at Simple.Data.Ado.AdoAdapter.RunQuery(SimpleQuery query, IEnumerable`1& unhandledClauses) in 
at Simple.Data.Ado.AdoAdapter.<RunQueries>d__10.MoveNext() in 
at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) in 
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source) in 
at Simple.Data.SimpleQuery.RunWithCount() in 
at Simple.Data.SimpleQuery.Run() in 
at Simple.Data.SimpleQuery.GetEnumerator() in

**Comment by ThatRendle** [comment]
Do you have more than one .Select(...) clause in your query? As far as I can see that's the only thing that could cause this problem.

**Comment by ThatRendle** [comment]
I've added some code inside SimpleQuery itself to throw an InvalidOperation exception at the point where an attempt is made to add a Select clause to a query that already has one.

**Comment by Vidarls** [comment]
Looking at my culprit query now:
It has:
- two explicit join statements, 
- one Where statement, with four conditions
- one select statement with columns form the two joined in tables, none from the base table.
- one WIthtotalcount statement

**Comment by ThatRendle** [comment]
OK, thanks for the update. I'll take a look in a bit.

On Wed, Aug 10, 2011 at 8:33 AM, Vidarls
reply@reply.github.com
wrote:

**Comment by craiggwilson** [comment]
Two Select Clauses isn't a problem in and of itself.  In fact, linq supports multiple select clauses. It should be left up to the adapter on whether or not it can handle this.  If it cannot, then it can return those as unhandledClauses and let the in memory version handle that so the query still works.

**Comment by ThatRendle** [comment]
I can't think of a scenario where having two select clauses makes sense.

On Wed, Aug 10, 2011 at 3:06 PM, craiggwilson
reply@reply.github.com
wrote:

**Comment by craiggwilson** [comment]
It wouldn't from a server perspective necessarily, but the 2nd select statement could be run locally.  I understand if you don't want to support it, but IF you are going to support the unhandledClauses thing, then it doesn't matter if it is there or not. 

If you are on a kick to get rid of all invalid server queries, then a skip after a take doesn't make any sense and a where clause, while it can be executed after a skip or take, doesn't really make much sense either.

BTW: in your RunWithCount() method, you are adding a second Select clause.

**Comment by ThatRendle** [comment]
Ah, that's where it's coming from. I need to replace the Select rather
than adding another one. D'oh! I'll fix that in a bit.

For the time being, I'm going to stick with the single Select clause,
because it makes sense to me. I've done some work on a
DynamicEnumerable type which implements the full set of LINQ methods,
and which would just segue into queries almost unnoticeably, so that
could handle LINQ style selects when I integrate it.

Sent from my iPad

On 10 Aug 2011, at 19:23, craiggwilson
reply@reply.github.com
wrote:

**Comment by craiggwilson** [comment]
While you are in there, can we remove the WithTotalCount clause base from the non-count query...

**Comment by ThatRendle** [comment]
Yup :)

**Comment by Vidarls** [comment]
What's the status on this
I was just trying to do a WithTotalCount in some demo code and got a "Query already contains a select clause" back from simple.data.

Code that poduced this result:

Future<int> count; (is future of int, but brackets got filtered out.)
var result = _db.Breeds.Query()
  .WithTotalCount(out count)
  .Where(_db.Breeds.Species.Name == p.speciesname)
  .Select(_db.Breeds.Name, _db.Breeds.Species.Name.As("Speciesname"));

Run against a SqlCompact db

**Comment by ThatRendle** [comment]
I'll have it fixed by Sunday night, and get those slides to you too. 

M

**Comment by ThatRendle** [comment]
Fixed, 0.9.2.1 on NuGet.
