### ISSUE TITLE
Skip & Take not working in certain Joins 

### ISSUE THREAD

**Issue by smartsense-as** [ThatRendle/Simple.Data#76]
When you create a Join to another table that has a column with the same name, and try retrieve both columns with the same name in the Select clause, skip and take cease to function. I can see the problem straight away in the generated SQL:

WITH __Data AS (SELECT [dbo].[Companies].[Name],[dbo].[Requirements].[Date],[dbo].[PeriodTypes].[Name] AS [Period], ROW_NUMBER() OVER(ORDER BY [dbo].[Companies].[Name]) AS [_#_]
from [dbo].[Requirements] JOIN [dbo].[Companies] ON ([dbo].[Companies].[CompanyId] = [dbo].[Requirements].[ChartererId]) JOIN [dbo].[PeriodTypes] ON ([dbo].[PeriodTypes].[PeriodTypeId] = [dbo].[Requirements].[PeriodTypeId]) WHERE ([dbo].[Requirements].[RequirementStateId] = @p1 AND [dbo].[Companies].[CompanyTypeId] = @p2))
SELECT [Name],[Date],[Name] AS [Period] FROM __Data WHERE [_#_] BETWEEN @skip + 1 AND @skip + @take
@p1 (Int32) = 1
@p2 (Int32) = 3
@skip (Int32) = 1
@take (Int32) = 10

**Comment by ThatRendle** [comment]
Oops. Fixed, will be in 0.9.1 release, on NuGet by end of this week.
