### ISSUE TITLE
Out of Memory Exception When Updating Binary Column (SqlCe)

### ISSUE THREAD

**Issue by charlescook** [ThatRendle/Simple.Data#78]
I get an out of memory exception when updating a binary column (type image in my case). The Size property of the SqlCeParameter is being set to 1073741823 here:

```
        public IDbDataParameter CreateParameter(string name, Column column)
        {
            var sqlCeColumn = (SqIDbDataParameterlCeColumn) column;
            return new SqlCeParameter(name, sqlCeColumn.SqlDbType, column.MaxLength, column.ActualName);
        }
```

The Size property shouldn't be set to the MaxLength value. According to MSDN:

> The Size property is used for binary and string types.
> 
> For nonstring data types and ANSI string data, the Size property refers to the number of bytes. For Unicode string data, Size refers to the number of characters. The count for strings does not include the terminating character.
> 
> For variable-length data types, Size describes the maximum amount of data to transmit to the server. For example, for a Unicode string value, Size could be used to limit the amount of data sent to the server to the first 100 characters.
> 
> For bidirectional and output parameters, and return values, you must set the value of Size. This is not required for input parameters, and if not explicitly set, the value of is inferred from the actual size of the specified parameter when a parameterized statement is executed.

**Comment by ThatRendle** [comment]
Bother. OK, nice quick fix, I'll push a point release out later today.

**Comment by ThatRendle** [comment]
OK, since SqlCe doesn't have bidirectional or output parameters, I've changed this code to set Size to 0.

0.9.3.2 on NuGet now.

Thanks for the detailed bug report, the extra effort is very much appreciated.

**Comment by charlescook** [comment]
Thanks, I'll try it later today.
