### ISSUE TITLE
Exception: No valid exports were found that match the constraint '((exportDefinition

### ISSUE THREAD

**Issue by chaliy** [ThatRendle/Simple.Data#79]
After starting with Simple.Data first exception I had were:

> No valid exports were found that match the constraint '((exportDefinition.ContractName == "Ado") AndAlso exportDefinition.Metadata.ContainsKey("ExportTypeIdentity") AndAlso "Simple.Data.Adapter".Equals(exportDefinition.Metadata.get_Item("ExportTypeIdentity"))))', invalid exports may have been rejected.

Exception sounds quite unfriendly. Resolution was easy, I just need to place Simple.Data.SqlServer.dll and Simple.Data.Ado.dll into the folder with Simple.Data.dll.

How this situation occured:
1. I have lib, that uses Simple.Data;
2. I reference this lib to the console app;
3. I am running console app, and get this exception;

Visual Studio do not copies all required assemblies because Simple.Data uses them implicitly. This is easy, so as solution.

May be you can provide (I can do pull request) copy of the database opener directly in Simple.Data.SqlServer.dll, so if somebody will use version from Simple.Data.SqlServer.dll Visual Studio automatically copy all required assemblies as expected? Current solution is just add new SqlConnectionProvider(); somewhere in code, this makes Visual Studio aware that we need this lib.

Other possible option, is to improve error message, because for newbies it really sounds scarry :).

**Comment by ThatRendle** [comment]
Improved error message in 0.9.4.
