### ISSUE TITLE
Issue with Find, multiple schemas, and duplicate table names

### ISSUE THREAD

**Issue by smwhit** [ThatRendle/Simple.Data#8]
Slightly obscure one here - but it's causing problems against our db.

Two schemas. A table in either schema named ApplicationLog.

An API call to db.dbo.ApplicationLog.Find(db.dbo.ApplicationLog.Message == "Application starting"); blows up with "System.InvalidOperationException : Sequence contains more than one element"
The stacktrace makes it quite clear what is going on:
at System.Linq.Enumerable.SingleOrDefault(IEnumerable`1 source)
at Simple.Data.Ado.Schema.TableCollection.FindTableWithName(String tableName)
 instead of calling the overload with a schema in it.

FindAllBy syntax seems to work just fine.

**Comment by ThatRendle** [comment]
I will investigate...

**Comment by ThatRendle** [comment]
Fixed. Thanks for the catch.
