### ISSUE TITLE
RuntimeBinderException when casting to IEnumerable<dynamic> 				

### ISSUE THREAD

**Issue by object** [ThatRendle/Simple.Data#80]
When using FindAll if I write statements like this:

```
        IEnumerable<dynamic> packages = db.Packages.FindAllByTitle("ABC");
```

then I get the following exception:

Microsoft.CSharp.RuntimeBinder.RuntimeBinderException : Cannot implicitly convert type 'Simple.Data.SimpleQuery' to 'System.Collections.Generic.IEnumerable<dynamic>'. An explicit conversion exists (are you missing a cast?)

But if I postfix the expression with Cast:

```
        IEnumerable<dynamic> packages = db.Packages.FindAllByTitle("ABC").Cast<dynamic>();
```

then everything works fine.

**Comment by ThatRendle** [comment]
Fixed in 0.9.4.
