### ISSUE TITLE
upgrading simple.data.oracle

### ISSUE THREAD

**Issue by flq** [ThatRendle/Simple.Data#81]
I have opened a branch to update Simple.Data.Oracle for the latest in Simple.Data. Upgrade has been fairly smooth and most of the new features also work. Where I have an issue is with the following:

```
        Promise<int> count;
        List<dynamic> list = _db.Employees.QueryByEmployeeId(100.to(125))
            .Take(10)
            .WithTotalCount(out count)
            .ToList();

        Assert.IsTrue(count.HasValue);
        Assert.AreEqual(10, list.Count);
        Assert.AreEqual(25, count);
```

It fails with a Stackoverflow(!) exception. Do you have any clues as to what is done recursively in that area?

Secondly, I may be wrong but thought that Generated SQL was being output during the tests - I cannot see any output. Was there an output and how do I get it back?

**Comment by ThatRendle** [comment]
I have this test in my Sql test project:

```
    [Test]
    public void WithTotalCountShouldGiveCount()
    {
        Promise<int> count;
        var db = DatabaseHelper.Open();
        var list = db.PagingTest.QueryById(1.to(50))
            .Take(10)
            .WithTotalCount(out count)
            .ToList();

        Assert.AreEqual(10, list.Count);
        Assert.IsTrue(count.HasValue);
        Assert.AreEqual(50, count);
    }
```

and it runs OK, so I don't think the problem is in the core code.

Generated SQL should be output to the trace, but it doesn't seem to show up in ReSharper. Hm.

**Comment by flq** [comment]
Yup, that's the test I copied for mine ;) If you are not aware of any recursive structure in your code I suppose I'll have to investigate with a build...

Some more information:

The recursion happens in AdoAdapter.RunQueryWithCount (106) - In 124 it hits an enumerator returned from "RunQueries", which somehow comes back to said method "RunQueryWithCount".

Another Update:

In "RunQueries" there is a big if..else where something entirely different happens when the provider doesn't support compound statements. This should be the answer as to why the behaviour is different since oracle doesn't support compound statements, which is the reason why my provider states 'false'...

**Comment by ThatRendle** [comment]
Yeah, I know what's happening there. Fixing it now.

**Comment by ThatRendle** [comment]
OK, it's fixed. Serves me right for not having a test for WithTotalCount against SQL Compact provider.

**Comment by flq** [comment]
Awesome stuff! Getting there..:)
