### ISSUE TITLE
Support for anonymous types in Find

### ISSUE THREAD

**Issue by object** [ThatRendle/Simple.Data#85]
Currently Find method requires that columns in search criteria are specified using dynamic properties, e.g.:

var product = db.Products.Find(db.Products.ProductName == "Chai");

This works fine, however in some cases an alternative syntax can be useful:

var product = db.Products.Find(new {ProductName == "Chai"});

An example when the latter syntax can be more convenient if the search criteria comes from other place and was built using other technique (e.g. LINQ). Moreover, this notation does not drag prefix "db.Products." so it can also be more compact.

And resolution of anonymous types by Simple.Data will be simple: extract properties of the anonymous type instance and build the filter similar to dynamic-based approach.

**Comment by ThatRendle** [comment]
Yeah, alright then.
