### ISSUE TITLE
InputOutput parameters with sending in null results in exception

### ISSUE THREAD

**Issue by tcartwright** [ThatRendle/Simple.Data#91]
Steps to recreate: 

1) Create a stored procedure with a an output parameter with a default value.
create procedure TestInputOutputs
    @Id int = null output,
    @CreatedDate datetime = null output,
    @LastModifiedDate datetime = null output
as
    set nocount on
    select @Id = 100, @CreatedDate = getdate(), @LastModifiedDate = getdate()
go

2) When calling the procedure from simple.data pass null or dbnull.value as the parameter value
            var ret = db.TestInputOutputs(
                Id: DBNull.Value,
                CreatedDate: null,
                LastModifiedDate: null
            );

result: Exception "the Size property has an invalid size of 0."

I have made a couple small changes to the source code to fix this. Let me know if you want then, and how I can get them to you. Maybe email?  I am unfamiliar with git, so I don't know how else to get them to you.

**Comment by ThatRendle** [comment]
Fixed.
